EPMRPP-45156 Releases page
reportportal/reportportal-website pull request #111
Opened 2020-01-08 16:58 UTC by AmsterGet

2020-01-09 14:50 UTC, DiscoElevator requested changes

2020-01-09 14:50 UTC, DiscoElevator commented on src/views/pages/releases-page/index.js
> +    const async = $.Deferred();
It's better to avoid using reserved names as identifiers

2020-01-09 14:50 UTC, DiscoElevator commented on src/views/pages/releases-page/releasesAPI.js
> +    const safetyKey = key.toString().replace(/\./gi, DOT_REPLACEMENT_SEQUENCE);
Is it possible to avoid this replacement?

2020-01-09 14:50 UTC, DiscoElevator commented on src/views/pages/releases-page/releasesAPI.js
> +          matches[issueId] = `[${issueId}](https://github.com/reportportal/reportportal/issues/${issueId})`;
Let's hope that every issue will be from the same repository and actually an issue, not PR

2020-01-09 15:42 UTC, AmsterGet commented on src/views/pages/releases-page/releasesAPI.js
> +    const safetyKey = key.toString().replace(/\./gi, DOT_REPLACEMENT_SEQUENCE);
Fixed

2020-01-09 15:43 UTC, AmsterGet commented on src/views/pages/releases-page/releasesAPI.js
> +          matches[issueId] = `[${issueId}](https://github.com/reportportal/reportportal/issues/${issueId})`;
Let's :)

2020-01-09 15:49 UTC, AmsterGet commented on src/views/pages/releases-page/index.js
> +    const async = $.Deferred();
Fixed

2020-01-10 08:23 UTC, DiscoElevator approved these changes

2020-01-10 08:23 UTC, merged