EPMRPP-63601: add new labels and fix styles
reportportal/reportportal-website pull request #128
Opened 2021-07-15 08:44 UTC by oranje322

2021-07-16 07:21 UTC, chivekrodis requested changes

2021-07-16 07:21 UTC, chivekrodis commented on src/views/pages/installation-page/installation-page_integrate/installation-page_integrate.jade
> +              img(src=require("./img/codecept.png"))
please recheck this agent status

2021-07-16 07:21 UTC, chivekrodis commented on src/views/pages/installation-page/installation-page_integrate/installation-page_integrate.jade
> +            a(href='https://github.com/reportportal/agent-js-webdriverio', data-js-new-window)
this agent is not released yet

2021-07-22 09:51 UTC, AmsterGet approved these changes

2021-07-22 09:51 UTC, merged