EPMRPP-64279: change tryDemo to askPricing button on mobile view
reportportal/reportportal-website pull request #131
Opened 2021-07-22 14:59 UTC by oranje322

2021-07-22 15:24 UTC, chivekrodis requested changes

2021-07-22 15:24 UTC, chivekrodis commented on src/views/components/modals/askPricingModal/index.js
>    },
Does it method is necessary?

2021-07-22 15:42 UTC, oranje322 commented on src/views/components/modals/askPricingModal/index.js
>    },
if delete this method, modal will not close when click outside

2021-07-22 16:21 UTC, chivekrodis commented on src/views/components/modals/askPricingModal/index.js
>    },
The `resize` method doesn't implement an any logic to close a modal by clicking on the background.
In my opinion you should remove `resize` method, in all places where it is used and check it again.
Also, remove unnecessary import `selectize`.
`onDestroy` unnecessary too.

2021-07-23 07:35 UTC, chivekrodis requested changes

2021-07-23 07:35 UTC, chivekrodis commented on src/views/pages/index-page/index-page_welcome/index.js
> +    Router.modals.show(new AskPricingModal());
Please, make sure that modal window is display correctly on mobile view up to 375px

2021-07-26 22:11 UTC, AmsterGet approved these changes

2021-07-26 22:15 UTC, merged