EPMRPP-66129: add hover effect for video
reportportal/reportportal-website pull request #145
Opened 2021-09-24 11:41 UTC by oranje322

2021-09-24 11:59 UTC, chivekrodis requested changes

2021-09-24 11:59 UTC, chivekrodis commented on src/views/pages/pageSectionMixin.scss
>          display: $displayProperty;
Please, remove the display property and mixin argument, this is no longer needed

2021-09-27 08:35 UTC, chivekrodis approved these changes

2021-09-28 07:09 UTC, AmsterGet approved these changes

2021-09-28 07:10 UTC, merged