EPMRPP-74453 || Leave social media icons only in footer
reportportal/reportportal-website pull request #158
Opened 2022-02-16 13:54 UTC by Vadim73i

2022-02-17 09:26 UTC, AmsterGet requested changes
The menu items should be centered (see the screenshot below).

![image](https://user-images.githubusercontent.com/31861805/154445659-48886fef-659f-4b5a-ac5a-08f844e49dc9.png)

Page should be called **Pricing**.

Also please add a pricing menu item to mobile view.

![image](https://user-images.githubusercontent.com/31861805/154445897-344f72d9-6019-4f60-93e3-d99d2da3d87f.png)

2022-02-17 09:43 UTC, chivekrodis requested changes

2022-02-17 09:43 UTC, chivekrodis commented on src/views/components/footer/Footer.scss
> +          margin-left: 5px;
Please add white background for the github tooltip

2022-02-17 09:43 UTC, chivekrodis commented on src/views/components/header/Header.scss
> -            }
It doesn't seem to need to be removed.. Please recheck mobile view, we have side panel

2022-02-17 09:43 UTC, chivekrodis commented on src/views/components/header/index.js
> -    $('[data-js-github-stars-container]', this.$el).html(this.gitHubStarsCount.$el);
`data-js-github-stars-container` necessary container for side panel

2022-02-18 08:08 UTC, chivekrodis requested changes

2022-02-18 08:08 UTC, chivekrodis commented on src/views/components/footer/Footer.scss
> +          background-color: #ffffff;
Please replace it with variable `$COLOR-WHITE_TWO`

2022-02-18 12:04 UTC, AmsterGet approved these changes

2022-02-18 12:04 UTC, merged