EPMRPP-74455 || Add tabs switcher component
reportportal/reportportal-website pull request #161
Opened 2022-02-18 21:25 UTC by Vadim73i

2022-02-20 13:49 UTC, chivekrodis requested changes

2022-02-20 13:49 UTC, chivekrodis commented on src/react-components/plans-block/plansBlock.jsx
> +const SMALL_SWITCHER_WIDTH = 188;
What the reason extracted that data into variable? Looks like Switcher component include all necessary data inside, you can manage it via props like size or something similar to it.

2022-02-20 13:49 UTC, chivekrodis commented on src/react-components/plans-block/plansBlock.jsx
> +const data = [
I know that it's mock data, name `data` it's ok in case of it only one var in the file, but in case of using that all vars in the future please use more meaningful name

2022-02-20 13:49 UTC, chivekrodis commented on src/react-components/plans-block/plansBlock.jsx
> +};
Please move it inside `plansBlock` component. if you will use it in the future

2022-02-20 13:49 UTC, chivekrodis commented on src/react-components/plans-block/plansBlock.jsx
> +    <Switcher className={BIG_SWITCHER_CLASSNAME} itemsData={data3} handleSelect={handleSwitcherItemSelect} switcherWidth={BIG_SWITCHER_WIDTH} isItemsEqualWidth />
Does it possible reorganize data and just iterate through them?

2022-02-20 13:49 UTC, chivekrodis commented on src/react-components/pricing-page/pricingPage.jsx
> +const PRICING_PAGE_CLASSNAME = 'pricing-page';
Does that variable will be using more than one time? Really necessary extract it to the variable?

2022-02-20 13:49 UTC, chivekrodis commented on src/react-components/switcher/switcher.jsx
> +    const id = e.currentTarget.id;
You can get `id` directly from `onClick={(id) => onClick(item.id)}`. No necessary save data directly in html

2022-02-20 13:49 UTC, chivekrodis commented on src/react-components/switcher/switcher.jsx
> +      style={{ width: switcherWidth }}
Please do not use inline styles, better manage it via scss

2022-02-20 13:49 UTC, chivekrodis commented on src/react-components/switcher/switcher.jsx
> +        : { ...item, isActive: false }),
Can be shorten `item => ({ ...item, isActive: item.id === id ? true : false }`

2022-02-20 13:49 UTC, chivekrodis commented on src/react-components/switcher/switcher.jsx
> +    }
What the reason search active item for the first time? You can pre define it in the data

2022-02-20 22:49 UTC, Vadim73i commented on src/react-components/switcher/switcher.jsx
> +        : { ...item, isActive: false }),
Can be even shorter `item => ({ ...item, isActive: item.id === id })` =)

2022-02-21 13:14 UTC, chivekrodis commented on src/react-components/plans-block/plansBlock.scss
> +  width: 618px;
Make sure that using strict width size don't break layout while resize

2022-02-21 13:14 UTC, chivekrodis commented on src/react-components/switcher/switcher.jsx
>            id={item.id}
it doesn't seem to be needed anymore

2022-02-21 13:52 UTC, AmsterGet commented on src/react-components/switcher/switcher.jsx
>    isSeparatorNeeded: false,
May be better `withSeparator`?

2022-02-21 13:52 UTC, AmsterGet commented on src/react-components/switcher/switcher.jsx
> +        isSeparatorNeeded && 'with-separator',
May be better to use such conditional classes as an object?
```javascript
{
   'equal-width': isItemsEqualWidth,
   'with-separator': withSeparator,
}
```
Looks more declarative.

2022-02-21 14:48 UTC, chivekrodis approved these changes

2022-02-21 15:14 UTC, merged