EPMRPP-74457 || Implement "Do you have questions" form without actions
reportportal/reportportal-website pull request #162
Opened 2022-02-21 16:54 UTC by Vadim73i

2022-02-21 18:57 UTC, chivekrodis commented on src/react-components/questions-form/questionsForm.jsx
> +  };
onChange funcs looks the same for all fields, does it possible use only one func and manage setValue and onError via params?
Also, maybe better compile state into one object

2022-02-21 18:57 UTC, chivekrodis commented on src/react-components/questions-form/questionsForm.jsx
> +      <div className="form">
I'm not sure but please make sure this form shouldn't be salesforce form

2022-02-22 07:17 UTC, AmsterGet requested changes

2022-02-22 07:17 UTC, AmsterGet commented on src/react-components/button/button.jsx
> +  text: PropTypes.string,
Can you pass it through the `children` prop?

2022-02-22 07:17 UTC, AmsterGet commented on src/react-components/questions-form/questionsForm.scss
> +        display: table-cell;
What is the purpose of displaying it as `table-cell` outside of the table?

2022-02-22 07:19 UTC, AmsterGet commented on src/react-components/questions-form/questionsForm.jsx
> +      <div className="form">
For now it should be just empty form without action. Salesform fields will be migrated to react in the scope of future task.

2022-02-22 07:54 UTC, AmsterGet approved these changes

2022-02-22 07:59 UTC, AmsterGet approved these changes

2022-02-22 07:59 UTC, merged