EPMRPP-75878 || minor bug fixing
reportportal/reportportal-website pull request #180
Opened 2022-03-25 13:49 UTC by Vadim73i

2022-03-28 07:15 UTC, chivekrodis requested changes
Also, please fix the error from the console

2022-03-28 07:15 UTC, chivekrodis commented on src/react-components/forms/custom-field/customField.jsx
> +const CustomField = ({
Maybe just `FormField`?

2022-03-29 06:50 UTC, AmsterGet requested changes

2022-03-29 06:50 UTC, AmsterGet commented on src/react-components/forms/contact-form/contactForm.jsx
> +              type='text'
Type `text` looks like a default value for inputs, can we omit it?

2022-03-29 07:06 UTC, chivekrodis approved these changes

2022-03-29 09:43 UTC, AmsterGet approved these changes

2022-03-29 09:43 UTC, merged