EPMRPP-76331 || Adopt styles for Pricing page based on CSS modules
reportportal/reportportal-website pull request #182
Opened 2022-04-01 09:09 UTC by Vadim73i

2022-04-01 10:23 UTC, chivekrodis requested changes

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/plans-block/plansBlock.jsx
> +            withFullClock={withFullClock}
Why you manage  `'with-clock'` class here in case of you pass `withClock={withClock}` prop inside component?
Look like with-clock, with-full-clock classes should be in the PlanCard component

2022-04-01 10:23 UTC, chivekrodis commented on src/common/css/variables/screen-variables.scss
> +$SCREEN_SM_MAX: 991px; //todo 1024
add new end point or remove comment. If you want specify some endpoint which will bi used in one place you can do it directly in the .scss file

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/common/button/button.jsx
> +  light: PropTypes.bool,
Maybe better instead of bool `light` use `variant` or `appearance` prop to be more flexible and pass string 'light', 'dark' etc.

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/forms/contact-form/contactForm.scss
> +    width: 18px;
remove `width` property and manage it with margin

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/forms/form-field/formField.scss
> +  width: 420px;
By default field should be flexible and span the entire width. Manage width with layout

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/forms/form-field/formField.scss
> +  $marginBetweenFields: 36px;
Please move it to the top right after comment

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/forms/form-field/formField.scss
> +  width: calc(50% - #{$marginBetweenFields}/2);
By default field should be flexible and span the entire width. Manage width with layout

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/forms/form-field/formField.scss
> +.form-field:not(.with-icon) {
Why you use it? We have regular formField and extended like formField with icon. `form-field:not(.with-icon)` should be regular formField or not?

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/forms/form-field/formField.scss
> +  }
remove it

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/forms/form-field/formField.scss
> +    $marginAroundFields: 15px;
Use standard media query from constants `scree-variables.scss` 
Move all constant to the top of the file right after comment section

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/forms/questions-form/questionsForm.scss
> +}
For what is it right now?

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/pricing-page/pricingPage.scss
> +@media all and (max-width: 320px) {
You repeat `max-width: 1024px` `max-width: 320px` couple times
extracte it to the constants

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/common/switcher/switcher.jsx
> +    if (!element.active && !element.inactive) {
What the state between active and inactive?

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/common/table/table.scss
>      .header-cell {
What the reason use nesting if the 2 top classes are empty?

2022-04-01 10:23 UTC, chivekrodis commented on src/react-components/plan-card/planCard.scss
> +  margin-left: 67px !important;
it's bad practice using !important

2022-04-01 10:36 UTC, Vadim73i commented on src/common/css/variables/screen-variables.scss
> +$SCREEN_SM_MAX: 991px; //todo 1024
This comment for next tablet view task.

2022-04-01 10:38 UTC, chivekrodis commented on src/common/css/variables/screen-variables.scss
> +$SCREEN_SM_MAX: 991px; //todo 1024
You are using this breakpoint couple time in current PR

2022-04-01 11:01 UTC, Vadim73i commented on src/react-components/common/button/button.jsx
> +  light: PropTypes.bool,
Why are
`<Button  variant='light'}>hello</Button>` and `<Button  variant='light big round'}>hello</Button>`
better than 
`<Button  light>hello</Button>` and `<Button  light big round>hello</Button>`
?
We can't influence the component's styles in this case.
What benefit does this give us?

2022-04-01 11:12 UTC, chivekrodis commented on src/react-components/common/button/button.jsx
> +  light: PropTypes.bool,
light, dark, filled, outline is the general variants of the button. one prop resolve all variant.
big, small, rounded Corner etc. it's just small embellishment and extracted into separate props to have the ability to combine it together or not use it at all
also a lot of properties in the component make it bigger and messy.

2022-04-01 11:25 UTC, chivekrodis commented on src/react-components/common/button/button.jsx
> +  light: PropTypes.bool,
upd. big/small usually extracting to `size` property they must not overlap

2022-04-04 12:42 UTC, chivekrodis requested changes
Your last commit affect header panel. Please don't use selecting by tag name in scss use classes instead
upd. release page too

2022-04-04 15:22 UTC, chivekrodis approved these changes

2022-04-04 16:31 UTC, AmsterGet approved these changes

2022-04-04 16:31 UTC, AmsterGet commented on src/common/css/variables/screen-variables.scss
> +$SCREEN_IPAD: 1024px;
Hope the screen breakpoints will be unified between landing page and service-ui repos.

2022-04-04 16:32 UTC, merged