EPMRPP-76310 || Add animations to landing pricing page
reportportal/reportportal-website pull request #183
Opened 2022-04-05 09:08 UTC by Vadim73i

2022-04-05 10:00 UTC, AmsterGet requested changes

2022-04-05 10:00 UTC, AmsterGet commented on src/react-components/common/info-with-tooltip/infoWithTooltip.scss
> +  transition: opacity 0.3s, visibility 0.3s;
`visibility` property is not animated.
See https://stackoverflow.com/questions/27900053/css-transition-with-visibility-not-working

2022-04-05 10:00 UTC, AmsterGet commented on src/react-components/common/info-with-tooltip/infoWithTooltip.scss
> +    z-index: 1;
Please move it to SCSS variables.

2022-04-05 10:46 UTC, chivekrodis requested changes

2022-04-05 10:46 UTC, chivekrodis commented on src/common/css/variables/color-variables.scss
> +$COLOR-WHITE-CARD-SHADOW-WITH-OPACITY: #eaeced90;
Does it really necessary extract into own property color with opacity?
maybe better do it directly in the file like `rgba(color, opacity)`

2022-04-05 10:46 UTC, chivekrodis commented on src/react-components/common/custom-checkbox/customCheckbox.scss
> +    transition: 0.3s;
better add property which you want to animate. Animate everything is not such good practice

2022-04-05 10:46 UTC, chivekrodis commented on src/react-components/plan-card/simple-card/simpleCard.scss
> +
I guess you can create the same scale animation with `transform: scale(1.05)` property without complicate the code

2022-04-05 17:09 UTC, chivekrodis approved these changes

2022-04-06 11:14 UTC, AmsterGet approved these changes

2022-04-06 11:14 UTC, merged