EPMRPP-76310 || Pricing page adapdation for mobile and tablet
reportportal/reportportal-website pull request #184
Opened 2022-04-08 13:37 UTC by Vadim73i

2022-04-11 05:49 UTC, chivekrodis requested changes
Please recheck side panel for tablet view. Page should't be scrollable while panel is open

2022-04-11 05:49 UTC, chivekrodis commented on src/react-components/common/info-with-tooltip/infoWithTooltip.jsx
> +  isMobileView: PropTypes.bool,
Please remove unused prop

2022-04-13 13:59 UTC, AmsterGet requested changes

2022-04-13 13:59 UTC, AmsterGet commented on src/react-components/common/info-with-tooltip/infoWithTooltip.jsx
> +  const onClick = () => {
Move it upper to the component where it is used. You can render another component to show modal without mixing the behavior of tooltip and modal.

2022-04-13 13:59 UTC, AmsterGet commented on src/react-components/layouts/modal-layout/modal-popup/modalPopup.jsx
> +    <div className={cx('contact-form')}>
Is it a `contact-form` or smth common?
Please name the component as `NotificationModalLayout` or smth like that.

2022-04-13 13:59 UTC, AmsterGet commented on src/react-components/plan-card/planCard.jsx
> +  const backTo = getIsMobileView() ? 'Back to package' : null;
Seems like you already manage the mobile or non mobile view via [CSS](https://github.com/reportportal/reportportal.github.io/pull/184/files#diff-fb9602f7bda260763de24644dfeaaa71243b64f61251f181f15489c46098ea12R61). It will be enough for this case.

2022-04-13 20:35 UTC, AmsterGet commented on src/react-components/layouts/modal-layout/modal/modal.jsx
> +          className={cx('close-button', { 'without-mobile-close-button': withoutMobileCloseButton })}
Why not just `{ hidden: withoutMobileCloseButton }`?

2022-04-13 20:35 UTC, AmsterGet commented on src/react-components/layouts/modal-layout/modal-popup/notificationModal.jsx
> +export default NotificationModal;
Please rename its folder also to `notification-modal`.

2022-04-14 06:18 UTC, AmsterGet approved these changes

2022-04-14 06:19 UTC, merged