EPMRPP-76684 || Privacy/Cookie Policy and Marketing checkboxes are not unchecked after sending the form
reportportal/reportportal-website pull request #188
Opened 2022-04-20 13:41 UTC by Vadim73i

2022-04-20 13:45 UTC, tr1ble approved these changes

2022-04-21 07:56 UTC, AmsterGet requested changes

2022-04-21 07:56 UTC, AmsterGet commented on src/react-components/forms/salesforce-form-base/salesForceFormBase.jsx
>      <input type='hidden' name='debug' value='1'/>
Also please remove this one.

2022-04-21 07:56 UTC, AmsterGet commented on src/react-components/forms/contact-form/contactForm.jsx
> +            <FormFieldWrapper name='00N5t000000hwUy'>
The goal of this wrapper is to connect specific field with form. Could you please wrap checkbox component inside with this wrapper?

2022-04-21 15:07 UTC, AmsterGet commented on src/react-components/forms/form-field-wrapper/formFieldWrapper.jsx
> +import {useField} from 'formik';
`import { useField } from 'formik';`

2022-04-21 15:13 UTC, AmsterGet approved these changes

2022-04-21 15:13 UTC, merged