EPMRPP-76706 || Use env variables to configure SalesForce URL
reportportal/reportportal-website pull request #189
Opened 2022-04-25 06:49 UTC by Vadim73i

2022-04-25 08:20 UTC, chivekrodis approved these changes

2022-04-26 17:49 UTC, AmsterGet requested changes

2022-04-26 17:49 UTC, AmsterGet commented on src/react-components/forms/contact-form/contactForm.jsx
> +            action={process.env.SALESFORCE_URL}
Please create a config file named f.e. `salesforceConfig` and use such variables there, e.g.
```javascript
{
  url: process.env.SALESFORCE_URL,
  oid: process.env.SALESFORCE_OID,
}
```

2022-04-27 08:56 UTC, AmsterGet approved these changes

2022-04-27 08:57 UTC, merged