EPMRPP-76702 || Privacy/Cookie Policy links are missing on the bottom of the website (footer)
reportportal/reportportal-website pull request #193
Opened 2022-04-28 12:50 UTC by Vadim73i

2022-04-28 15:36 UTC, chivekrodis approved these changes

2022-04-28 15:46 UTC, AmsterGet requested changes

2022-04-28 15:46 UTC, AmsterGet commented on src/utils/backboneReactRender.js
>  }
This utility tries to change smth outside it, so it may lead to errors and unexpected behavior while using it.
I suggest to change this function in the following way to add an ability to control it from outside:
```javascript
export default function renderReactComponent(container, ReactComponent) {
  const component = new ReactComponent({ model: null, el: container });
  container.append(component.render());
  
  return component;
}
```

In this case usage will look like this:
```javascript
const container = $('[some selector here]', this.$el);
// save the reference of the component if needed
this.view = renderReactComponent(container, HeaderButtons);
```

2022-04-29 06:53 UTC, AmsterGet commented on src/views/components/header/index.js
> +    this.view = renderReactComponent(middleBlock, HeaderButtons);
Why are you override it?
If you need to hold reference to the component, use unique name. Otherwise remove references at all.

2022-04-29 07:20 UTC, AmsterGet approved these changes

2022-04-29 07:24 UTC, merged