EPMRPP-76692 || pricing page. use new breakpoints for mobile and tablet views
reportportal/reportportal-website pull request #195
Opened 2022-05-10 14:19 UTC by Vadim73i

2022-05-10 18:19 UTC, chivekrodis requested changes

2022-05-10 18:19 UTC, chivekrodis commented on src/react-components/plans-block/constants.js
> +export const PACKAGE_168 = 'Package 168+';
You extracted them to the variables but they are still not are variables. If we change for smallest package from 32 hours to 31 you must to change variable name(PACKAGE_32 -> PACKAGE_31 because PACKAGE_32=package 31 seems confused) and in every places where it used so better name it more general by size(small, medium) or something similar to it

2022-05-10 18:19 UTC, chivekrodis commented on src/react-components/plans-block/plan-cards/planCards.jsx
> +  const plans = {
Looks like you duplicate `<SimpleCard>` many times. Better store data somewhere and iterate over it.

2022-05-12 09:53 UTC, chivekrodis approved these changes

2022-05-12 11:31 UTC, AmsterGet commented on src/react-components/forms/questions-form/questionsForm.jsx
> +        For more details please leave your e-mail and we will contact you within 4 business days.
Is it a part of requirements?

2022-05-12 11:31 UTC, AmsterGet commented on src/react-components/header/header-buttons/headerButtons.jsx
> +    document.body.classList.remove('side-open');
Why we need this?

2022-05-12 15:33 UTC, AmsterGet approved these changes

2022-05-12 15:33 UTC, merged