EPMRPP-77303 || Landing. Fix space between switchers on pricing page
reportportal/reportportal-website pull request #198
Opened 2022-05-17 09:22 UTC by Vadim73i

2022-05-17 09:24 UTC, tr1ble approved these changes

2022-05-17 09:28 UTC, AmsterGet requested changes

2022-05-17 09:28 UTC, AmsterGet commented on src/react-components/common/switcher/switcher.scss
> +      &.with-point + .with-point {
May be better `.with-point` + '.item'?

2022-05-17 09:28 UTC, AmsterGet commented on src/react-components/common/switcher/switcher.scss
> +      .with-point + .with-point {
Same here.

2022-05-17 09:28 UTC, AmsterGet commented on src/react-components/common/switcher/switcher.jsx
>            <div className={cx('item', {'with-point': withPoint})}>
If you add `'with-point'` class to the parent, why you need to duplicate it here?
Just use corresponding selector.

2022-05-17 09:28 UTC, chivekrodis approved these changes

2022-05-18 10:24 UTC, AmsterGet approved these changes

2022-05-18 10:24 UTC, merged