EPMRPP-78279 || Use React production build for reportportal.io
reportportal/reportportal-website pull request #239
Opened 2022-08-09 10:59 UTC by Vadim73i

2022-08-09 11:05 UTC, chivekrodis commented on package.json
> +    "prod": "NODE_ENV='production' webpack serve",
Do we need it?

2022-08-09 11:07 UTC, Vadim73i commented on package.json
> +    "prod": "NODE_ENV='production' webpack serve",
So we can test the production build locally

2022-08-09 11:15 UTC, chivekrodis commented on package.json
> +    "prod": "NODE_ENV='production' webpack serve",
I see, but looks like we need it only one time and for developers

2022-08-09 11:31 UTC, AmsterGet requested changes

2022-08-09 11:31 UTC, AmsterGet commented on package.json
> +    "prod": "NODE_ENV='production' webpack serve",
We don't use this script in production so it looks a bit confusing.
I would suggest to remove it.

2022-08-09 11:33 UTC, AmsterGet requested changes

2022-08-09 11:33 UTC, AmsterGet commented on package.json
> +    "build": "NODE_ENV='production' webpack"
What about other parts of webpack config where the `env.production` used? Should we refactor such places?

2022-08-09 15:33 UTC, chivekrodis approved these changes

2022-08-12 08:56 UTC, AmsterGet commented
It looks like the new scripts don't work on Windows.
Don't merge until the changes are cross-platform.

2022-11-30 22:39 UTC, AmsterGet approved these changes

2022-12-01 10:51 UTC, merged