Installation Page
reportportal/reportportal-website pull request #327
Opened 2023-04-06 06:59 UTC by WebDevWorker

Currently working
![Screenshot 2023-04-06 095742](https://user-images.githubusercontent.com/129626513/230295924-f56dc12d-24b9-4ae6-a439-a669f9d5f85c.png)
 on the following thinks:
1. Switch buttons component.
2. installation header page

![Screenshot 2023-04-06 095742](https://user-images.githubusercontent.com/129626513/230295924-f56dc12d-24b9-4ae6-a439-a669f9d5f85c.png)

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/installation/icons/KubernetesIcon.jsx
> +export const KubernetesIcon = ({ color }) => (
Let's run it against svgo - https://jakearchibald.github.io/svgomg/

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/pages/instalallation.js
> +import { Inst } from '../components/installation';
```suggestion
import { Layout } from '../components/Layout';
import { Inst } from '../components/installation';

import '../styles/global.scss';
```

Please keep the order like that. First come third party ones, then local ones, then styles

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/installation/components/Notice/Notice.scss
> +  &__border{
```suggestion
  &__border {
```

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/installation/components/Notice/Notice.scss
> +    padding-left: var(--space-2xl);
```suggestion
    @include font-noto-sans();

    padding-left: var(--space-2xl);
```

Let's add empty line after mixins

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/installation/Inst.jsx
> +export const Inst = () => {
Let's name it `Installation`

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/installation/Inst.jsx
> +    console.log('=== handleSwitch ====>', data);
Let's remove it

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/installation/Inst.jsx
> +    setContentState((previous) => !previous);
Let's use `useBoolean` hook from `ahooks` lib

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/switchButtons/SwitchButtons.tsx
> +      return false
```suggestion
      return false;
```

Lets use semi for consistency

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/installation/Inst.scss
> +  &__title {
```suggestion
  color: var(--white);
  
  &__title {
```

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/installation/Inst.scss
> +$header-height: 76px;
Lets define it on global level and use it everywhere

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/installation/Inst.scss
> +.bg {
Lets prefix it

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/switchButtons/SwitchButtons.scss
> +    @include font-poppins($fw-semi-bold);
Let's place mixins (except `breakpoint` one) at the top

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/installation/Inst.jsx
> +      <DockerIcon color={item.active ? 'var(--color-primary-500)' : 'var(--white)'} />
Let's manage the color in CSS only via classname. See how it is done for other icons

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/installation/Inst.scss
> +    color: var(--primary);
Let's not use --primary. It comes from initial boilerplate, I have not removed it as it was used in couple places. The same is applicable to --white variable. Only this variables should be used - https://github.com/reportportal/reportportal.github.io/blob/new-landing/src/styles/variables.scss#L61-L105

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/switchButtons/SwitchButtons.tsx
> +      <div className="switch__inner" style={{maxWidth: getWidth()}}>
```suggestion
      <div className="switch__inner" style={{ maxWidth: getWidth() }}>
```

Is prettier not handle it?

But the issue actually again managing it in styles. You can put the width on each button and it will expand the inner width

2023-04-11 09:18 UTC, ViktorSoroka07 commented on src/components/switchButtons/SwitchButtons.tsx
> +  const getWidth = () =>  BUTTON_WIDTH * switchState.length
```suggestion
  const getWidth = () => BUTTON_WIDTH * switchState.length
```
Is prettier not handle it?

2023-04-12 06:16 UTC, WebDevWorker commented on src/components/switchButtons/SwitchButtons.tsx
> +      <div className="switch__inner" style={{maxWidth: getWidth()}}>
Currently, I haven't managed to implement it in another way. Could we temporarily merge this variant?

2023-04-12 07:51 UTC, ViktorSoroka07 approved these changes

2023-04-13 08:37 UTC, AmsterGet requested changes
In general, please name component's directories using `PascalCase`.
Also I suggest to move common components (that can be used across different pages) to the `components/core` or `components/common` directory. Currently you can do it for `Notice` and `SwitchButton` components. cc @ViktorSoroka07

2023-04-13 08:37 UTC, AmsterGet commented on src/components/switchButtons/SwitchButtons.scss
> +
Please remove extra empty line.

2023-04-13 08:37 UTC, AmsterGet commented on src/components/installation/components/Notice/Notice.tsx
> +  <div className="notes">
Use `getBlocksWith()`.

2023-04-13 08:37 UTC, AmsterGet commented on src/pages/instalallation.js
Please rename file to `installation` to provide correct routing capabilities.

2023-04-13 08:37 UTC, AmsterGet commented on src/components/installation/components/Notice/Notice.tsx
> +const getBlocksWith = createBemBlockBuilder(['notes']);
Please use the `className` based on the component name:
`notice` instead of `notes`.
Please recheck all other components.

2023-04-13 08:40 UTC, AmsterGet commented on src/components/switchButtons/SwitchButtons.tsx
> +      <div className="switch__inner" style={{maxWidth: getWidth()}}>
@WebDevWorker @ViktorSoroka07 
I would have preferred Viktor's suggestion, but it looks like this component will be changed anyway as part of the `Pricing` page development as it will support URL integration. So let's postpone the refactoring until this improvement.

2023-04-13 14:28 UTC, AmsterGet approved these changes

2023-04-13 14:29 UTC, merged