Text content
reportportal/reportportal-website pull request #334
Opened 2023-04-18 07:44 UTC by WebDevWorker

![Screenshot 2023-04-18 104335](https://user-images.githubusercontent.com/129626513/232707398-4d3cb387-b595-4b6c-95d1-07355f539787.png)

2023-04-19 11:19 UTC, ViktorSoroka07 commented on src/components/installation/Installation.scss
> +  border: 1px solid #EDEFF7;
variable

2023-04-19 11:19 UTC, ViktorSoroka07 commented on src/components/installation/Installation.scss
> +    @include breakpoint($tablet-lg) {
empty line

2023-04-19 11:19 UTC, ViktorSoroka07 commented on src/components/installation/Installation.scss
> +      line-height: 24px;
Can we use mixin?

2023-04-19 11:19 UTC, ViktorSoroka07 commented on src/components/installation/Installation.scss
> +      &:hover {
empty line

2023-04-19 11:19 UTC, ViktorSoroka07 commented on src/components/installation/Installation.scss
> +        fill: var(--text-light-grey);
Can you use currentColor on svg instead?

https://gomakethings.com/currentcolor-and-svgs/

2023-04-19 11:19 UTC, ViktorSoroka07 commented on src/components/installation/components/DockerContent/DockerDeployingStep.tsx
> +          <a className={getBlocksWith('__link')} href="#">{' '}
Is `{' '}` really needed?

2023-04-19 11:19 UTC, ViktorSoroka07 commented on src/styles/mixins/font.scss
> +
```suggestion

```

2023-04-19 11:19 UTC, ViktorSoroka07 commented on src/styles/mixins/font.scss
> +  @include font-info($weight, $font-style);
You need to add file to `src/styles/font` to support it. See how it is done for other fonts

2023-04-19 20:16 UTC, WebDevWorker commented on src/components/installation/Installation.scss
> +        fill: var(--text-light-grey);
I don't have access to this svg icon

2023-04-19 20:19 UTC, WebDevWorker commented on src/components/installation/components/DockerContent/DockerDeployingStep.tsx
> +          <a className={getBlocksWith('__link')} href="#">{' '}
When the next word is started from a new line a space disappears. This construction is necessary

2023-04-20 12:14 UTC, ViktorSoroka07 commented on src/components/installation/Installation.scss
> +        // fill: currentColor; //var(--text-light-grey);
Should it be removed?

2023-04-21 15:39 UTC, ViktorSoroka07 approved these changes

2023-04-26 13:30 UTC, AmsterGet requested changes

2023-04-26 13:30 UTC, AmsterGet commented on src/components/ButtonSwitcher/ButtonSwitcher.jsx
> +    return true;
We don't expect any return value of this function, so the `return` statement can be omitted here.

2023-04-26 13:30 UTC, AmsterGet commented on src/components/ButtonSwitcher/ButtonSwitcher.jsx
> +      return false;
Let it be just `return` as this function should return nothing.

2023-04-26 13:30 UTC, AmsterGet commented on src/components/InstallationPage/components/DockerContent/DockerContent.jsx
> +    <div>
Is an empty `div` required here?

2023-04-26 13:30 UTC, AmsterGet commented on src/components/InstallationPage/components/DockerContent/DockerDeployingStep.jsx
> +            -c max_parallel_workers_per_gather=`,
What is the reason of duplicating it here?
Can we just use the template string as a component's children to avoid using `<br />` tags?

2023-04-26 13:30 UTC, AmsterGet commented on src/styles/mixins/font.scss
> +  font-family: 'Roboto Mono', Arial, sans-serif;
Please contact design team about relevant fallbacks for this font.
Usually console-like formatting fonts has better alternatives than `Arial` and `sans-serif`.
F.e. the main RP application uses the next sequence of fallbacks:
`Menlo, Monaco, Consolas, 'Courier New', monospace`

2023-04-26 13:53 UTC, AmsterGet requested changes

2023-04-26 13:53 UTC, AmsterGet commented on src/components/ButtonSwitcher/ButtonSwitcher.jsx
> +  const [switchState, setSwitchState] = useState(buttons);
Can we hold just active button `id` here?
As I see the only one button can be active at a time, so in this case we can avoid duplicating prop's `buttons` in state and simply change the `activeButtonId` during switch action.

2023-04-27 15:06 UTC, AmsterGet approved these changes

2023-04-27 15:06 UTC, AmsterGet commented on src/components/InstallationPage/InstallationPage.scss
> +     white-space: pre-wrap;
Please remove extra space

2023-04-27 15:07 UTC, merged