New landing Pricing page
reportportal/reportportal-website pull request #342
Opened 2023-05-11 08:07 UTC by WebDevWorker

![pricing](https://github.com/reportportal/reportportal.github.io/assets/129626513/05949c98-b717-4d64-b77a-49d82d3a9696)

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/styles/buttons.scss
> +
Can be combined

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/pages/pricing.js
> +import { PricingPage } from '../components/PricingPage';
```suggestion
import React from 'react';

import { Layout } from '../components/Layout';
import { PricingPage } from '../components/PricingPage';
```

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/icons/ServerIcon.jsx
> +import React from 'react';
Let's use approach that I shared with you about .inline about all svg images

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/PricingCards/pricingData.js
> +    description: `Access to a project space in a multi-tenant setup with all the premium
Let's use backticks only when needed. Let's manage line breaks in CSS by setting width as I am not sure in future this data will come in this format. Check other places

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/DiscountSwitcher/DiscountSwitcher.jsx
> +        discountState ? getSwitcherBlock('__switcher-active') : '',
```suggestion
        [getSwitcherBlock('__switcher-active')]: Boolean(discountState),
```

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/ComparePlans/ComparePlans.scss
> +
Remove

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/PricingCards/PricingCard/index.js
> +export * from './PricingCard';
Empty line needed. Run prettier script

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/PricingCards/PricingCards.scss
> +  >div {
Can we just add class to avoid such selector?

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/PricingCards/PricingCards.scss
> +      ul {
This one I think can be omitted

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/PricingCards/PricingCards.jsx
> +    {pricingData &&
Is this a real case that `pricingData ` can be empty? In this case I would add this check above the div above.

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/PricingCards/PricingCards.jsx
> +const getPricingCards = createBemBlockBuilder(['cards']);
This is too general name. Don't forget that this class will be sort of global. Let's come up with more unique names for classes

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/ComparePlans/icons/Arrow.jsx
> +//  <svg xmlns="http://www.w3.org/2000/svg" width="28" height="23" fill="none">
Remove. Also, let's use .inline approach. You can manage rotation via class I think

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/ComparePlans/Columns.jsx
> +  const [visibility, setVisibility] = useState(true);
Let's name boolean variables with verb (`is`, `should`, etc) prefix.
```suggestion
  const [isVisible, setIsVisible] = useState(true);
```

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/ComparePlans/Columns.jsx
> +              style={{ fontSize: `${fontSize}px` }}
Let's manage it via CSS. We have mixins for that

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/ComparePlans/Columns.jsx
> +    if (str < 3) {
```suggestion
    if (str.length < 3) {
```
Was this the intent?

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/ComparePlans/Columns.jsx
> +                [getCompareContainer('__row-title-col-font')]: bigFont,
Let's remove the prop. Assign the class or multiple classes on the element and manage the font there

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/PricingCards/PricingCard/PricingCard.jsx
> +const getPricingCard = createBemBlockBuilder(['card']);
Need more unique classname

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/ComparePlans/ComparePlans.jsx
> +  const isNotRow = (section, footer) => section || footer;
```suggestion
  const isRow = (section, footer) => !(section || footer);
```
So it is easier to reed it when you need to check for `not a row` - `!isRow`. `!isNotRow` means that you check for row, but it is harder to reason about.

2023-05-26 10:30 UTC, ViktorSoroka07 commented on src/components/PricingPage/PricingPage.jsx
> +  const [discountState, { toggle }] = useToggle(true);
`toogle` need another name

2023-05-26 14:06 UTC, WebDevWorker commented on src/components/PricingPage/components/PricingCards/PricingCards.scss
> +  >div {
I prefer this variant if you don't mind. Because this class is from another component and can be renamed. It will be hard to keep it under controll

2023-05-30 11:06 UTC, ViktorSoroka07 approved these changes, later dismissed

2023-05-30 11:08 UTC, ViktorSoroka07 commented on src/styles/buttons.scss
> +    }
```suggestion
    }
```

2023-05-30 11:09 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/ComparePlans/ComparePlans.scss
> +    cursor: auto;
```suggestion
    margin: 20px 0;
    cursor: auto;
```

2023-05-30 11:13 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/ComparePlans/ComparePlans.jsx
> +  };
```suggestion
  const getArrowAngle = (isActive) => {
    let angle;

    if (isActive) {
      angle = isDesktop ? 90 : -90;
    } else {
      angle = isDesktop ? 0 : 90;
    }

    return angle;
  };
```

2023-05-30 11:16 UTC, ViktorSoroka07 commented on .vscode/settings.json
Should we remove this file? I remember @AmsterGet asked mentioned about that, but I am not sure

2023-05-30 15:52 UTC, AmsterGet requested changes

2023-05-30 15:52 UTC, AmsterGet commented on src/components/PricingPage/PricingPage.jsx
> +  const [activeButton, setActiveButton] = useState(ACTIVE_BUTTON);
The exact Pricing page should be opened via link.
So the user should be able to go to the Saas/On-Premises view directly via link.

![image](https://github.com/reportportal/reportportal.github.io/assets/31861805/664697df-8e44-4592-8de4-57af202ea5fd)

So please connect component to the URL to support such behavior.
The particular view can be determined f.e. using URL query parameters.

2023-05-30 15:52 UTC, AmsterGet commented on src/components/PricingPage/components/ComparePlans/ComparePlans.jsx
> +      {!isDesktop && <div className={getCompareContainer('__tab-title')}>Main functionality</div>}
Can we join these two conditions?


```suggestion
      {isDesktop ? (
          <ColumnsHeader title="Features" />
      ) : (
          <div className={getCompareContainer('__tab-title')}>Main functionality</div>
      )}
```

2023-05-30 15:52 UTC, AmsterGet commented on src/components/PricingPage/components/ComparePlans/Description.jsx
> +  const formComponent = (str, anchorHref) => {
Why do you create the component during render?
Can we avoid it at all and leave only one component here?

2023-05-30 15:52 UTC, AmsterGet commented on src/components/PricingPage/components/Organizations/Organizations.jsx
> +  const isTablet = useMediaQuery({ query: '(min-width: 769px)' });
Use global constant for `'(min-width: 769px)'`.

2023-05-30 15:52 UTC, AmsterGet commented on src/components/PricingPage/components/ComparePlans/RowSection.jsx
> +export const RowSection = ({ footer }) => {
What is `RowSection` component for?
I see that you mix some footer related blocks with others.
Can we split it to independent components and not mix the behavior and purpose in one place?

2023-05-30 15:52 UTC, AmsterGet commented on src/components/PricingPage/components/ComparePlans/RowSection.jsx
> +      {isDesktop && (
Why we don't use CSS here to hide it for mobile?

2023-05-30 15:52 UTC, AmsterGet commented on src/components/PricingPage/components/PricingCards/PricingCard/PricingCard.jsx
> +const getPricingCard = createBemBlockBuilder(['pricing-card']);
Let's follow our agreements.
Rename to `getBlocksWith`

2023-05-30 15:52 UTC, AmsterGet commented on src/components/PricingPage/components/PricingCards/PricingCards.jsx
> +const getPricingCards = createBemBlockBuilder(['pricing-cards']);
Same here.

2023-06-01 11:50 UTC, WebDevWorker commented on src/components/PricingPage/PricingPage.jsx
> +  const [activeButton, setActiveButton] = useState(ACTIVE_BUTTON);
Let me ask you to put this task out of my work scope because I made some investigation and understood it is too big and I feel a lack of time extremely

2023-06-01 12:23 UTC, WebDevWorker commented on src/components/PricingPage/components/ComparePlans/RowSection.jsx
> +export const RowSection = ({ footer }) => {
I created this component to avoid a nested ternary operator issue in the code

2023-09-06 14:13 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.scss
> +        font-style: normal;
Is it needed?

2023-09-06 14:13 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.scss
> +        font-feature-settings: 'clig' off, 'liga' off;
I think this can be removed

2023-09-06 14:13 UTC, ViktorSoroka07 commented on src/components/PricingPage/faqData.js
> +    key: 7,
Let's use label as the key. Can we do that?

2023-09-06 14:13 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/PricingCards/pricingData.js
> +    id: 1,
Can we remove this field and use `title` for key?

2023-09-06 14:13 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/PricingCards/pricing-mock-data.js
Is this file needed?

2023-09-06 14:13 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/PricingCards/PricingCards.scss
> +@import 'src/styles/mixins/breakpoint';
```suggestion
@use 'src/styles/mixins' as m;
@use 'src/styles/variables' as v;
```

Please update files in this PR to follow this notation

2023-09-06 14:13 UTC, ViktorSoroka07 commented on src/components/PricingPage/components/PlanComare/PlanCompare.scss
> +      @include breakpoint($desktop-sm) {
```suggestion
      display: inline-block;
      position: relative;

      @include breakpoint($desktop-sm) {
```

2023-09-06 14:13 UTC, ViktorSoroka07 commented on src/components/Faq/Faq.scss
> +  @include horizontal-spacer();
Can we remove it and instead add `container` class from global.css?

2023-09-06 14:13 UTC, ViktorSoroka07 commented on src/components/Faq/Faq.scss
> +  color: #2f3c5f;
Please use variable. If it does not exist please ask the desinger

2023-09-07 08:43 UTC, OleksandrDragun commented on src/components/Faq/Faq.scss
> +@import 'src/styles/variables';
Could you please try using new approach with importing 
@use 'src/styles/mixins' as m;
@use 'src/styles/variables' as v;

2023-09-07 08:45 UTC, OleksandrDragun commented on src/components/Faq/Faq.scss
> +    line-height: 64px;
I'm sure that we have such values in font-scale mixin (x3-large).

2023-09-07 08:47 UTC, OleksandrDragun commented on src/components/Faq/Faq.scss
> +    @include breakpoint($desktop-size-breakpoint) {
According to readme we should use the next breakpoints
$tablet-sm-exact: 768px
$desktop-sm: 1239px
https://github.com/reportportal/reportportal.github.io/tree/new-landing#scsscss

2023-09-07 09:06 UTC, OleksandrDragun commented on src/components/PricingPage/components/ComparePlans/Columns.jsx
> +const Mark = ({ value }) =>
This is not worth moving such small component outside the main especially after main.
I think method renderMark is enough in this case or you can move it above the main component.

2023-09-07 09:14 UTC, OleksandrDragun commented on src/components/PricingPage/components/ComparePlans/ComparePlans.jsx
> +const ExpandableRow = ({ feature, rowData }) => {
This component looks like smart and should be moved to separate file.

2023-09-07 09:16 UTC, OleksandrDragun commented on src/components/PricingPage/components/ComparePlans/Columns.jsx
> +import React, { useEffect, useState } from 'react';
Why do we need components folder inside PricingPage? If you create something inside it definitely belongs to PricingPage.

2023-09-07 09:21 UTC, OleksandrDragun commented on src/components/PricingPage/components/ComparePlans/ComparePlans.scss
> +      line-height: 20px;
It is better to discuss redeclaration of line-height rule after using global font-scale mixin with designer because it is ok. Styles should be approximately the same through all the app.

2023-09-07 09:24 UTC, OleksandrDragun commented on src/components/PricingPage/components/ComparePlans/ComparePlans.scss
> +        font-size: 24px;
This will be inherited from mobile.

2023-09-07 09:40 UTC, OleksandrDragun commented on src/components/PricingPage/components/Hero/Hero.scss
> +    background-position: center;
This will be inherited from tablet.

2023-09-07 09:43 UTC, OleksandrDragun commented on src/components/PricingPage/components/Organizations/Organizations.scss
> +    @include font-scale(medium);
Could you please add empty line here and remove it from 23 line,

2023-09-07 09:47 UTC, OleksandrDragun commented on src/components/PricingPage/components/PricingCards/PricingCard/PricingCard.scss
> +  @include breakpoint($phone) {
Do we need this breakpoint?

2023-09-07 09:51 UTC, OleksandrDragun commented on static/github.json
> +{"total":2601,"repos":{".github":0,"JBehaveSerenityAutomation":0,"JavaSDK":0,"agent-Python-RobotFramework":49,"agent-android":1,"agent-java-cucumber":22,"agent-java-cucumber2":0,"agent-java-cucumber3
Why do we need this file here?

2023-09-07 09:54 UTC, OleksandrDragun commented on src/utils/breakpoint.js
> +export const $phone = '(min-width: 411px)';
I guess we can leave only 3 main breakpoints. 
https://github.com/reportportal/reportportal.github.io/tree/new-landing#scsscss
Could you please discuss it with Viktor Soroka.

2023-09-07 10:42 UTC, OleksandrDragun commented
Could you please add this rule to eslintrc for avoiding creating more than one React component per file
"react/no-multi-comp":  [2, { "ignoreStateless": false }]
My comments are related to all files not only to one place. Please take a look PR again and fix it in all the places.
Some scss rules are duplicated when you use breakpoints and can be removed.

2023-09-11 11:05 UTC, AmsterGet reviewed
No additional comments from my side.
Just want to additionally highlight the comment from @OleksandrDragun to discuss the `line-height` and global `font-scale`s consistency with UX team.

2023-09-11 11:05 UTC, AmsterGet commented on src/components/PricingPage/components/Hero/Hero.scss
> +
Extra empty line.

2023-09-11 16:12 UTC, yelyzavetakhokhlova commented on src/components/PricingPage/faqData.js
> +    key: 7,
We can, but will have to still explicitly set the key value

2023-09-11 16:28 UTC, yelyzavetakhokhlova commented on src/components/PricingPage/components/ComparePlans/Columns.jsx
> +import React, { useEffect, useState } from 'react';
Do you mean that Columns should be placed in /PricingPage/components?

2023-09-11 16:36 UTC, yelyzavetakhokhlova commented on src/components/PricingPage/components/PricingCards/PricingCard/PricingCard.scss
> +  @include breakpoint($phone) {
Looks like it, content doesn't fit inside 630px card height for mobile, but for other breakpoints, it should be static

2023-09-11 19:10 UTC, OleksandrDragun commented on src/components/PricingPage/components/ComparePlans/Columns.jsx
> +import React, { useEffect, useState } from 'react';
I meant that PricingPage folder is the main. We have main folder and if you want to create some additional related to PricingPage there is no need to create components folder just create ComparePlans folder.
src/components/PricingPage/ComparePlans/ComparePlans.jsx
src/components/PricingPage/ComparePlans/Columns/Columns.jsx
src/components/PricingPage/ComparePlans/RowSection/RowSection.jsx
src/components/PricingPage/ContentToggleSwitcher/ContentToggleSwitcher.jsx
And so on. 
I just against of this )
src/**components**/PricingPage/**components**/ComparePlans/**components**/Columns/Columns.jsx

2023-09-11 19:21 UTC, ViktorSoroka07 submitted a review, later dismissed

2023-09-12 11:04 UTC, yelyzavetakhokhlova commented on src/components/PricingPage/components/ComparePlans/Columns.jsx
> +import React, { useEffect, useState } from 'react';
Moved out all of the components to the components folder, except for OnPremisesPage and SaasPage 😎

2023-09-12 11:05 UTC, yelyzavetakhokhlova commented on src/utils/breakpoint.js
> +export const $phone = '(min-width: 411px)';
Discussed with Viktor to do it outside of this PR

2023-09-12 11:07 UTC, yelyzavetakhokhlova commented
> Could you please add this rule to eslintrc for avoiding creating more than one React component per file "react/no-multi-comp": [2, { "ignoreStateless": false }] My comments are related to all files not only to one place. Please take a look PR again and fix it in all the places. Some scss rules are duplicated when you use breakpoints and can be removed.

I didn't add the rule, since there are a lot of other components that do not comply with this rule. However, I refactored everything that's in my PR to follow this rule. Discussed with Viktor to add this rule to the scope of another task.

2023-09-12 12:39 UTC, ViktorSoroka07 commented on src/utils/breakpoint.js
> +export const $phone = '(min-width: 411px)';
Yeah, it is risky now to test all places. This is PR is already too big

2023-09-13 13:37 UTC, yelyzavetakhokhlova commented
@OleksandrDragun @AmsterGet discussed with Dmytro to use font-size/line-height pairing as we have in our mixins and to not override them. Updated it everywhere

2023-09-14 12:08 UTC, OleksandrDragun commented on src/components/PricingPage/ComparePlans/Description.jsx
> +      const afterText = match[3];
Just suggestion
const [, beforeText, highlightedText, afterText] = match;

2023-09-14 12:11 UTC, OleksandrDragun commented on src/components/PricingPage/PriceSwitcher/PriceSwitcher.jsx
> +  const [isActive, setIsIsActive] = useState(false);
setIsActive will be enough

2023-09-14 12:13 UTC, OleksandrDragun commented on src/components/PricingPage/PriceSwitcher/PriceSwitcher.jsx
> +          [isActive]: 'contentToggleSwitcher__switcher--active',
I don't know how it works but try this option
'contentToggleSwitcher__switcher--active': isActive,

2023-09-14 12:14 UTC, OleksandrDragun commented on src/components/PricingPage/PriceSwitcher/PriceSwitcher.scss
> +    @include m.font-noto-sans();
Could you please set mixins first and than color.

2023-09-14 12:20 UTC, OleksandrDragun commented on src/components/PricingPage/PricingCards/PricingCard/PricingCard.scss
> +        border-radius: 100%;
Browser automatically change this to 50% for making circle.

2023-09-14 12:50 UTC, OleksandrDragun approved these changes

2023-09-14 12:50 UTC, ViktorSoroka07 approved these changes

2023-09-14 12:52 UTC, AmsterGet approved these changes

2023-09-14 12:52 UTC, merged