Fixes on Instalation page. New Landing page
reportportal/reportportal-website pull request #346
Opened 2023-05-16 07:48 UTC by WebDevWorker

Designer Feedback: I have incorporated the design changes suggested by the designer, ensuring a more visually appealing interface.

Code Quality: I have taken into account the code review comments and made necessary revisions to enhance the overall code quality.

Custom Popup Development: Instead of using the Ant Design popup, I have developed a custom popup using Schema. This custom implementation provides the ability to avoid some bugs.

The banner component and additional text were implemented:
![Screenshot 2023-05-22 110739](https://github.com/reportportal/reportportal.github.io/assets/129626513/e5a59ea4-8b27-48a3-975e-5e2ccfce8c79)

A new Idicator scroll behavior was implemented
![Screenshot 2023-05-22 110852](https://github.com/reportportal/reportportal.github.io/assets/129626513/74206ab5-7fc5-41ca-a79e-bea9f0ab1034)

A substantial amount of time was dedicated to working on the "integration by languages" components, including:

Component Extraction: I have extracted a specific component from the existing codebase and performed necessary improvements and modifications to ensure its seamless integration.

Tab Redesign: I have revamped the tab functionality using the Ant Design library, as depicted in the attached image. This new implementation provides flexibility on different devices that were not implemented before.
![Screenshot 2023-05-22 102047](https://github.com/reportportal/reportportal.github.io/assets/129626513/9b1f08ac-97c2-4ae6-94e5-02a839643ef3)

2023-05-23 10:11 UTC, ViktorSoroka07 commented on src/components/SupportedFrameworks/SupportedFrameworks.jsx
> +import * as styles from './SupportedFrameworks.module.scss';
Is this temporal to use module css?

2023-05-23 10:11 UTC, ViktorSoroka07 commented on src/components/InstallationPage/components/IntegrationScheme/SchemeRow.jsx
> +  const ref2 = useRef(null);
We need better names

2023-05-23 10:11 UTC, ViktorSoroka07 commented on src/components/ScrollIndicator/ScrollIndicator.jsx
> +  const [offSet, setOffSet] = useState(-FIRST_POSITION_OFFSET);
```suggestion
  const [offset, setOffset] = useState(-FIRST_POSITION_OFFSET);
```

2023-05-23 10:11 UTC, ViktorSoroka07 commented on src/components/ScrollIndicator/ScrollIndicator.jsx
> +  const [heroPassed, setHeroPassed] = useState(false);
What does it mean `heroPassed`?

2023-05-23 10:11 UTC, ViktorSoroka07 commented on src/components/ScrollIndicator/ScrollIndicator.jsx
> +const HERO_HIGHT = 500;
Should it be like that?
```suggestion
const HERO_HEIGHT = 500;
```

2023-05-23 10:11 UTC, ViktorSoroka07 commented on src/components/ScrollIndicator/ScrollIndicator.jsx
> +  const [bottom, setBottom] = useState(-DEFAULT_BOTTOM_LINE_POSITION);
```suggestion
  const [topPosition, setTopPosition] = useState(0);
  const [bottomPosition, setBottomPosition] = useState(-DEFAULT_BOTTOM_LINE_POSITION);
```

2023-05-23 10:11 UTC, ViktorSoroka07 commented on src/components/ScrollIndicator/ScrollIndicator.jsx
> +                    smooth={true}
```suggestion
                    spy
                    smooth
```

2023-05-23 10:11 UTC, ViktorSoroka07 commented on src/components/InstallationPage/components/Banner/Banner.jsx
> +        <a href="https://slack.epmrpp.reportportal.io/">
Should the link open in new tab? Consider using link component in components folder

2023-05-23 10:11 UTC, ViktorSoroka07 commented on src/components/InstallationPage/components/Banner/Banner.jsx
> +        <a href="https://slack.epmrpp.reportportal.io/">
I don't think we have the combination of link and button at the same time. Use only one of them. In this case button should not be used.

2023-05-23 10:11 UTC, ViktorSoroka07 commented on src/components/InstallationPage/components/IntegrationContent/IntegrationContent.jsx
> +          <a
The same about link

2023-05-23 10:20 UTC, WebDevWorker commented on src/components/SupportedFrameworks/SupportedFrameworks.jsx
> +import * as styles from './SupportedFrameworks.module.scss';
It depends on what is our aim. Should I get rid of using CSS modules here?

2023-05-23 13:10 UTC, WebDevWorker commented on src/components/InstallationPage/components/IntegrationContent/IntegrationContent.jsx
> +          <a
It seems to me that the Link component doesn't work correctly and as I haven't understood what's wrong I prefer using my way temporarily if you don't mind. I don't want to change the component because the it used in many places

2023-05-24 10:45 UTC, ViktorSoroka07 submitted a review, later dismissed

2023-05-24 20:56 UTC, AmsterGet requested changes
Please check the `active` state of the

2023-05-24 20:56 UTC, AmsterGet commented on src/components/InstallationPage/components/IntegrationContent/IntegrationContent.jsx
> +          <Link className={getBlocksWith('__link')} target="_blank">
Seems like that `to="https://github.com/reportportal/reportportal"` prop missed here.

2023-05-24 20:56 UTC, AmsterGet commented on src/components/Footer/Footer.scss
> +  z-index: 10;
I'm not sure, but may be keep all `z-index`es as constants in some place to easier control layers overlapping in the future?
cc @ViktorSoroka07

2023-05-24 20:56 UTC, AmsterGet commented on src/components/InstallationPage/InstallationPage.jsx
> +                  <div key="section-2" name="section-2" id="part-2">
Do we need `key` attribute here?

2023-05-24 20:56 UTC, AmsterGet commented on src/components/InstallationPage/components/Banner/Banner.jsx
> +        </Link>
Please check the `active` state for this link (see the screenshot below):

![image](https://github.com/reportportal/reportportal.github.io/assets/31861805/e4fe0a08-2a06-4f39-a2b9-ab33a09452ab)

The text should be visible in this state as well.

2023-05-24 20:56 UTC, AmsterGet commented on src/components/SupportedFrameworks/SupportedFrameworks.jsx
> +            <Tabs
Can we style the tabs according to designs?
Figma:

![image](https://github.com/reportportal/reportportal.github.io/assets/31861805/ae4c45d1-ffb1-41d9-ace9-839254eb20e8)

Current implementation:

![image](https://github.com/reportportal/reportportal.github.io/assets/31861805/78611942-3578-4fe9-8f9c-da93bdcb2f78)

2023-05-24 20:56 UTC, AmsterGet commented on src/components/SupportedFrameworks/SupportedFrameworks.jsx
> +              onTabClick={(tabKey) => setActiveLanguage(tabKey)}
```suggestion
              onTabClick={setActiveLanguage}
```

2023-05-24 20:56 UTC, AmsterGet commented on src/components/SupportedFrameworks/SupportedFrameworks.jsx
> +              <img src={icon} />
I assume the elements should be links.
Could you please discuss it with design team and PO?

2023-05-24 20:56 UTC, AmsterGet commented on src/components/SupportedFrameworks/SupportedFrameworks.jsx
> +              defaultActiveKey="java"
I see several duplications of using this value.
Can we move it to constant together with other keys of supported languages?

2023-05-24 20:56 UTC, AmsterGet commented on src/components/InstallationPage/components/IntegrationScheme/IntegrationScheme.jsx
> +  const [state, { toggle }] = useToggle(true);
Can we use more meaningful name like `collapsed` or `expanded` instead of just `state` ?

2023-05-24 20:56 UTC, AmsterGet commented on src/components/InstallationPage/components/IntegrationScheme/IntegrationScheme.scss
> +    z-index: 1000;
The same comment about `z-index` here and other files.
Can we decrease it to more reasonable value and move to variable?

2023-05-24 20:56 UTC, AmsterGet commented on src/components/InstallationPage/components/IntegrationScheme/IntegrationScheme.scss
> +    z-index: 1000;
Please also fix other `z-index` values in this file.
Some of them are incorrect values with `px`.

2023-05-24 20:56 UTC, AmsterGet commented on src/components/InstallationPage/components/IntegrationScheme/SchemeRow.jsx
>    const [state, { toggle }] = useToggle();
`isPopupOpen` or just `isOpen`.

2023-05-25 07:42 UTC, WebDevWorker commented on src/components/InstallationPage/components/Banner/Banner.jsx
> +        </Link>
Unfortunately, I can't find the situation when the text can disappear. Could you provide me with more information about this issue

2023-05-26 09:04 UTC, AmsterGet requested changes

2023-05-26 09:04 UTC, AmsterGet commented on .vscode/settings.json
> +{}
Please add `.vscode` to `.gitignore`.

2023-05-26 09:04 UTC, AmsterGet commented on src/styles/variables.scss
> +
Please remove extra empty lines.

2023-05-26 09:28 UTC, AmsterGet commented on .vscode/settings.json
> +{}
@WebDevWorker please remove this file as well.

2023-05-26 09:37 UTC, ViktorSoroka07 commented on package-lock.json
Why do we have changes in this file?

2023-05-26 09:39 UTC, ViktorSoroka07 commented on src/styles/variables.scss
> +  --footer-z-index: 10; // to hide the scroll indicator line
Can we use `--z-index` for footer case?

2023-05-26 09:41 UTC, ViktorSoroka07 commented on src/styles/buttons.scss
> +}
```suggestion
.btn--primary {
  &:hover,
  &:active {
    color: var(--white);
  }
}
```

2023-05-26 09:42 UTC, ViktorSoroka07 commented on src/components/SupportedFrameworks/dataSource.js
> +    icon: iconsFrameworks.st,
Why `st`?

2023-05-26 09:56 UTC, ViktorSoroka07 commented on src/components/SupportedFrameworks/SupportedFrameworks.scss
> +        }
Please do nesting here

2023-05-26 09:56 UTC, ViktorSoroka07 commented on src/components/SupportedFrameworks/SupportedFrameworks.scss
> +  }
Indentation

2023-05-26 09:56 UTC, ViktorSoroka07 commented on src/components/SupportedFrameworks/SupportedFrameworks.jsx
> +                <img src={icon} />
The same questions you asked me about alt attribute

2023-05-26 09:56 UTC, ViktorSoroka07 commented on src/components/InstallationPage/components/IntegrationScheme/IntegrationScheme.scss
> +    z-index: $event-arrow-z-index;
CSS variables. There are many in the file similar cases. Please handle them all

2023-05-26 09:56 UTC, ViktorSoroka07 commented on src/components/InstallationPage/components/IntegrationScheme/IntegrationScheme.scss
> +    height: 12vw;
Why do use `vw`?

2023-05-26 09:56 UTC, ViktorSoroka07 commented on src/components/InstallationPage/components/IntegrationScheme/SchemeRow.jsx
> +  const [isPopupOpen, { toggle }] = useToggle();
```suggestion
  const [isPopupOpen, { toggle: togglePopupOpenState }] = useToggle();
```

2023-05-26 09:56 UTC, ViktorSoroka07 commented on src/components/InstallationPage/components/IntegrationScheme/IntegrationScheme.jsx
> +  const [collapsed, { toggle }] = useToggle(true);
`collapsed` what?

2023-05-26 09:56 UTC, ViktorSoroka07 commented on src/components/InstallationPage/InstallationPage.jsx
> +              <div name="section-4" id="part-4">
Why do we need `name` attribute on `div`? Not sure `id` is needed either

2023-05-26 09:56 UTC, ViktorSoroka07 commented on src/components/InstallationPage/components/Banner/Banner.scss
> +  background: linear-gradient(85.23deg, #F4F6FA 1.92%, #EEF0F7 53.85%);
Let's use variables for colors

2023-05-26 09:56 UTC, ViktorSoroka07 commented on src/components/InstallationPage/components/Banner/Banner.scss
> +    line-height: 48px;
This can be removed

2023-05-26 10:59 UTC, WebDevWorker commented on src/components/InstallationPage/components/IntegrationScheme/IntegrationScheme.scss
> +    height: 12vw;
to be the component flexible and have correct hight on smaller screens

2023-05-29 18:54 UTC, WebDevWorker commented on src/components/InstallationPage/components/Banner/Banner.scss
> +  background: linear-gradient(85.23deg, #F4F6FA 1.92%, #EEF0F7 53.85%);
These colors are not repeated in other places

2023-05-29 18:56 UTC, WebDevWorker commented on src/components/InstallationPage/components/IntegrationScheme/IntegrationScheme.scss
> +    z-index: $event-arrow-z-index;
Done

2023-05-29 19:09 UTC, WebDevWorker commented on src/components/InstallationPage/components/IntegrationScheme/IntegrationScheme.scss
> +    z-index: $event-arrow-z-index;
I would prefer to keep these variables locally because they are too specific and have too specific values. We can't reuse them.  What do you think about it?

2023-05-30 11:00 UTC, ViktorSoroka07 submitted a review, later dismissed

2023-05-30 15:29 UTC, AmsterGet requested changes

2023-05-30 15:29 UTC, AmsterGet commented on .vscode/settings.json
> +{}
@WebDevWorker ^^

2023-05-30 15:29 UTC, AmsterGet commented on src/components/InstallationPage/components/IntegrationScheme/IntegrationScheme.jsx
> +  const isDesktop = useMediaQuery({ query: '(min-width: 800px)' });
May be make sense to hold such media values `(min-width: 800px)` as constants?
Looks like it can used more than one time.

2023-06-08 12:07 UTC, AmsterGet approved these changes

2023-06-08 12:07 UTC, merged