features panel sticky and smooth scrolling
reportportal/reportportal-website pull request #357
Opened 2023-06-26 13:37 UTC by KrDior

1) Features links block sticky on scroll;
![image](https://github.com/reportportal/reportportal.github.io/assets/45118964/6a68ef26-ab51-4db7-a8e6-b080203f49b5)

2) Smooth scrolling on features links

2023-06-26 13:43 UTC, ViktorSoroka07 commented on src/components/Features/Features.jsx
> +});
Let's use `react-responsive` instead

2023-06-26 13:44 UTC, ViktorSoroka07 commented on src/components/Features/Features.jsx
> +  middle: 800,
Let's stick to this values for consistency $tablet-sm-exact: 768px $desktop-sm: 1239px;

2023-06-26 16:41 UTC, KrDior commented on src/components/Features/Features.jsx
> +});
fixed

2023-06-26 16:41 UTC, KrDior commented on src/components/Features/Features.jsx
> +  middle: 800,
fixed

2023-06-26 20:21 UTC, ViktorSoroka07 commented
Sometimes I see such state. Just click around to reproduce it
<img width="1354" alt="Screenshot 2023-06-26 at 23 20 25" src="https://github.com/reportportal/reportportal.github.io/assets/40821852/62d0cfd4-66ad-495c-bab0-c3abd300e069">

2023-06-26 20:23 UTC, ViktorSoroka07 commented
I am not sure the nav menu should be shown upon clicking the links when the page content is scrolled backward. I think it worth discussing it with the designers

2023-06-26 20:52 UTC, ViktorSoroka07 commented on src/components/Features/Features.scss
> +    }
Let's remove

2023-06-26 20:52 UTC, ViktorSoroka07 commented on src/components/Features/Features.jsx
> +    anchorTarget &&
Let's use `if` in such cases

2023-06-26 20:52 UTC, ViktorSoroka07 commented on src/components/Features/Features.jsx
> +import { useScroll, configResponsive } from 'ahooks';
```suggestion
import { useScroll } from 'ahooks';
```

2023-06-26 20:52 UTC, ViktorSoroka07 commented on src/components/Features/Features.jsx
> +import { useMediaQuery } from 'react-responsive';
Imports ordering issue

2023-06-27 09:30 UTC, KrDior commented on src/components/Features/Features.jsx
> +import { useMediaQuery } from 'react-responsive';
fixed

2023-06-27 09:30 UTC, KrDior commented on src/components/Features/Features.jsx
> +import { useScroll, configResponsive } from 'ahooks';
done

2023-06-27 09:30 UTC, KrDior commented on src/components/Features/Features.jsx
> +    anchorTarget &&
done

2023-06-27 09:30 UTC, KrDior commented on src/components/Features/Features.scss
> +    }
removed

2023-06-27 09:30 UTC, KrDior commented
> Sometimes I see such state. Just click around to reproduce it <img alt="Screenshot 2023-06-26 at 23 20 25" width="1354" src="https://user-images.githubusercontent.com/40821852/248926311-62d0cfd4-66ad-495c-bab0-c3abd300e069.png">

fixed

2023-06-27 09:32 UTC, KrDior commented
> I am not sure the nav menu should be shown upon clicking the links when the page content is scrolled backward. I think it is worth discussing it with the designers

discussed with Vitalii that we should show sticky menu after user click and scrolling to anchor element

2023-06-27 09:55 UTC, ViktorSoroka07 submitted a review, later dismissed

2023-06-27 09:56 UTC, ViktorSoroka07 approved these changes, later dismissed

2023-06-28 21:41 UTC, AmsterGet requested changes
General comments:

1. I see that features anchor links contains `link` prefix
![image](https://github.com/reportportal/reportportal.github.io/assets/31861805/8dc34aaa-8b4a-41ca-9433-e16468e211af)
I suppose that it is redundant to use this prefix. Can it be removed?

2. Looks like the navigation don't follow the chapters while scrolling
![image](https://github.com/reportportal/reportportal.github.io/assets/31861805/4da397cd-6195-4df3-aa46-e8d44c69a3af)
Please confirm with UX team is it applicable.

3. Looks like there are some z-index collisions between nav header and several blocks:
![image](https://github.com/reportportal/reportportal.github.io/assets/31861805/5c9ada52-9c4c-45cc-b88b-e7f15b2cafd2)
![image](https://github.com/reportportal/reportportal.github.io/assets/31861805/bcaab9b3-ca67-4da7-b48b-8485124d185d)
![image](https://github.com/reportportal/reportportal.github.io/assets/31861805/20905443-1b62-435d-8fc0-4b3061445299)

2023-06-28 21:41 UTC, AmsterGet commented on src/components/Features/Features.jsx
> +  const featuresBlockHeightWithHeader = featuresBlockHeight - headerHeight;
Looks like actually it is a featuresBlockHeight**Without**Header, am I right?

2023-06-28 21:41 UTC, AmsterGet commented on src/components/Features/Features.jsx
> +  const isDesktop = useMediaQuery({ query: '(min-width: 1239px)' });
Can we move this query `'(min-width: 1239px)'` to constant?
I see that it used several times.
It can be placed at `src/utils/variables.js` or even better extract it from utils to `src/constants/breakpoints.js` or smth like that.

2023-06-28 21:41 UTC, AmsterGet commented on src/components/Features/Features.jsx
> +  const handleNavClick = (event, id) => {
Seems like it is not an `id`, but the anchor link.
I suggest to name it as `link` or `anchor` and in that case it will be more clear what happened in this expression - `id.slice(1)`.

2023-06-29 15:15 UTC, KrDior commented on src/components/Features/Features.jsx
> +  const handleNavClick = (event, id) => {
renamed

2023-06-29 15:15 UTC, KrDior commented on src/components/Features/Features.jsx
> +  const isDesktop = useMediaQuery({ query: '(min-width: 1239px)' });
done

2023-06-29 15:16 UTC, KrDior commented on src/components/Features/Features.jsx
> +  const featuresBlockHeightWithHeader = featuresBlockHeight - headerHeight;
renamed to more clarity variables

2023-06-29 15:17 UTC, KrDior commented
> General comments:
> 
> 1. I see that features anchor links contains `link` prefix
>    ![image](https://user-images.githubusercontent.com/31861805/249420641-8dc34aaa-8b4a-41ca-9433-e16468e211af.png)
>    I suppose that it is redundant to use this prefix. Can it be removed?
> 2. Looks like the navigation don't follow the chapters while scrolling
>    ![image](https://user-images.githubusercontent.com/31861805/249621253-4da397cd-6195-4df3-aa46-e8d44c69a3af.png)
>    Please confirm with UX team is it applicable.
> 3. Looks like there are some z-index collisions between nav header and several blocks:
>    ![image](https://user-images.githubusercontent.com/31861805/249621519-5c9ada52-9c4c-45cc-b88b-e7f15b2cafd2.png)
>    ![image](https://user-images.githubusercontent.com/31861805/249621580-bcaab9b3-ca67-4da7-b48b-8485124d185d.png)
>    ![image](https://user-images.githubusercontent.com/31861805/249621642-20905443-1b62-435d-8fc0-4b3061445299.png)
pp.1,3 were fixed
p.2 will be implemented in the next commit

2023-06-30 15:31 UTC, AmsterGet commented
@ViktorSoroka07 could you please review it again as the logic changed and because I'll be OOO till July 10.

2023-07-01 16:38 UTC, ViktorSoroka07 commented on src/components/Features/Features.jsx
> +    lastScrollYRef.current = Math.max(scrollY, 0);
This is a repeated fragment from `Navigation.jsx`. Please create a [reusable hook](https://react.dev/learn/reusing-logic-with-custom-hooks) for it

2023-07-01 19:25 UTC, ViktorSoroka07 commented on src/components/Features/Features.jsx
> +      const offset = scrollDirection === 'up' ? rect.height * 0.9 : headerHeight;
What 0.9 means?

2023-07-02 15:56 UTC, ViktorSoroka07 commented on src/components/Features/Features.jsx
> +  const featuresBlockHeightWithHeader = featuresBlockHeight - headerHeight;
Still, it is not clear to me why here you use `With` instead of `Without`

2023-07-02 16:58 UTC, KrDior commented on src/components/Features/Features.jsx
> +      const offset = scrollDirection === 'up' ? rect.height * 0.9 : headerHeight;
Offset Coefficient (moved into variable)

2023-07-02 16:58 UTC, KrDior commented on src/components/Features/Features.jsx
> +    lastScrollYRef.current = Math.max(scrollY, 0);
done

2023-07-02 17:01 UTC, ViktorSoroka07 commented on src/custom-hooks/scroll-direction.jsx
Please use `useScrollDirection.jsx` for naming

2023-07-02 17:06 UTC, KrDior commented on src/custom-hooks/scroll-direction.jsx
renamed

2023-07-02 17:08 UTC, ViktorSoroka07 commented on src/components/Features/Features.jsx
> +              </div>
Please use changes from `new-landing` branch here. Is this changes are needed in your PR or it is the result of the rebases?

2023-07-02 17:12 UTC, ViktorSoroka07 commented on src/components/Navigation/Navigation.jsx
> +import { useScrollDirection } from '../../custom-hooks/useScrollDirection';
```suggestion
import { useScrollDirection } from '../../hooks/useScrollDirection';
```

And also, please create `index.js` file to reexport hooks so we can write in the way bellow

```suggestion
import { useScrollDirection } from '../../hooks';
```

2023-07-02 17:17 UTC, KrDior commented on src/components/Navigation/Navigation.jsx
> +import { useScrollDirection } from '../../custom-hooks/useScrollDirection';
fixed

2023-07-02 17:26 UTC, ViktorSoroka07 approved these changes

2023-07-02 17:27 UTC, merged