Implement Case Studies page based on the Contentfull
reportportal/reportportal-website pull request #377
Opened 2023-08-16 09:06 UTC by jinqiupeter

2023-08-16 10:42 UTC, ViktorSoroka07 commented on gatsby-node.js
> +  actions.setWebpackConfig({
Can you please clarify the purpose of this?

2023-08-16 10:42 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.jsx
> +import downloadIcon from './icons/download.svg';
```suggestion
import React from 'react';
import cx from 'classnames';

import { createBemBlockBuilder } from '../../utils';
import { SubscriptionBanner } from '../LandingPage/SubscriptionBanner/SubscriptionBanner';
import downloadIcon from './icons/download.svg';

import './CasesPage.scss';
```
Please follow this import convention to divide by empty line vendor, local and styles imports

2023-08-16 10:42 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.jsx
> +              backgroundSize: 'cover',
Please move this rule to the CSS

2023-08-16 10:42 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.jsx
> +      )}
Let's not render nothing in this case or even better please ask the designer Dmytro Nedilka what to do in this case

2023-08-16 10:42 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.scss
> +}
Please divide with empty lines nested imports and mixins blocks. Please adjust all similar cases.

```suggestion
.cases-page__no-more {
  display: flex;
  justify-content: center;
  align-items: center;
  margin-bottom: 120px;

  > p {
    color: var(--text-light-grey);
  }

  @include breakpoint($tablet-sm-exact) {
    margin-bottom: 200px;
  }
}
```

2023-08-16 10:42 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.scss
> +    border: 2px solid var(--primary-600, #009DBB);
No need for backup color. Please adjust all similar cases.
```suggestion
    border: 2px solid var(--primary-600);
```

2023-08-16 10:42 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.scss
> +@import 'src/styles/mixins/breakpoint';
Let's use `@use` approach. Check out how it is done in `SectionCard.scss`
```suggestion
@use 'src/styles/mixins' as m;
@use 'src/styles/variables' as v;
```

2023-08-16 10:42 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.scss
> +        @include font-poppins($fw-semi-bold);
Let's include mixins first. Please adjust similar cases

```suggestion
        @include font-poppins($fw-semi-bold);

        color: var(--white);
```

2023-08-16 10:55 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.jsx
> +      <SubscriptionBanner title="Stay in Know" />
```suggestion
      <SubscriptionBanner />
```

2023-08-16 10:56 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.jsx
> +import { SubscriptionBanner } from '../LandingPage/SubscriptionBanner/SubscriptionBanner';
Since this component is now used across multiple pages, please move it to the `components` folder.

2023-08-17 06:37 UTC, evsbvac commented on src/components/CasesPage/CasesPage.scss
> +  margin: 0px 24px 0px 24px;
Suggested
padding: 72px 0px 48px;
margin: 0px 24px;

2023-08-17 06:38 UTC, evsbvac commented on src/components/CasesPage/CasesPage.scss
> +    margin: 0px 120px 0px 120px;
margin: 0px 120px;

2023-08-18 18:05 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.scss
> +    @include breakpoint($tablet-sm) {
```suggestion
    @include breakpoint($tablet-sm-exact) {
```

2023-08-21 08:00 UTC, jinqiupeter commented on gatsby-node.js
> +  actions.setWebpackConfig({
Removed

2023-08-21 08:01 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.jsx
> +              backgroundSize: 'cover',
Fixed

2023-08-21 08:01 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.jsx
> +      )}
Removed

2023-08-21 08:01 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.scss
> +}
Fixed

2023-08-21 08:01 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.scss
> +    border: 2px solid var(--primary-600, #009DBB);
Fixed

2023-08-21 08:02 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.scss
> +@import 'src/styles/mixins/breakpoint';
Fixed

2023-08-21 08:02 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.scss
> +        @include font-poppins($fw-semi-bold);
Fixed

2023-08-21 08:02 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.jsx
> +      <SubscriptionBanner title="Stay in Know" />
Removed

2023-08-21 08:02 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.jsx
> +import { SubscriptionBanner } from '../LandingPage/SubscriptionBanner/SubscriptionBanner';
Moved to `components`

2023-08-21 08:02 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.scss
> +  margin: 0px 24px 0px 24px;
Fixed

2023-08-21 08:03 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.scss
> +    margin: 0px 120px 0px 120px;
Fixed

2023-08-21 08:06 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.scss
> +    @include breakpoint($tablet-sm) {
Fixed

2023-08-21 09:38 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.jsx
> +import downloadIcon from './icons/download.svg';
For the banner please create `index.js` file to reexport from it
```suggestion
import React from 'react';
import cx from 'classnames';

import { createBemBlockBuilder } from '../../utils';
import { SubscriptionBanner } from '../SubscriptionBanner';

import downloadIcon from './icons/download.svg';

import './CasesPage.scss';
```

2023-08-21 09:41 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.scss
> +        line-height: 32px; /* 160% */
What 160 means?

2023-08-21 09:41 UTC, ViktorSoroka07 commented on src/components/CasesPage/CasesPage.scss
> +        color: var(--white);
Please don't forget to add extra line after the mixins. There are more places in PR
```suggestion
        @include m.font-poppins(v.$fw-semi-bold);

        color: var(--white);
```

2023-08-22 09:59 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.jsx
> +import downloadIcon from './icons/download.svg';
Fixed

2023-08-22 09:59 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.scss
> +        line-height: 32px; /* 160% */
Removed. It was from Figma.

2023-08-22 09:59 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.scss
> +        color: var(--white);
Fixed

2023-08-23 10:08 UTC, AmsterGet requested changes
Please contact UX team on how to handle such cases in cards.

![image](https://github.com/reportportal/reportportal.github.io/assets/31861805/f70fb3f7-265c-42c4-9954-fe3f1b54d5fb)

2023-08-23 10:08 UTC, AmsterGet commented on src/pages/case-studies.jsx
> +    setDisplayCount(displayCount + 12);
Please move the default displayed number and step in the constant.

2023-08-23 11:40 UTC, ViktorSoroka07 commented
@jinqiupeter, please also make the `Explore Case Studies` button in the header menu to point to the Solutions section

2023-08-24 05:39 UTC, OleksandrDragun commented on src/components/CasesPage/CasesPage.jsx
> +    <div>
Suggestion of using Fragment here.

2023-08-24 05:41 UTC, OleksandrDragun commented on src/components/CasesPage/CasesPage.scss
> +    background-size: cover;
What is background-size for?

2023-08-24 07:11 UTC, jinqiupeter commented on src/pages/case-studies.jsx
> +    setDisplayCount(displayCount + 12);
Added

2023-08-24 07:12 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.jsx
> +    <div>
Refactored

2023-08-24 07:12 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.scss
> +    background-size: cover;
It's specifying the stype of the background image coming from CMS

2023-08-24 07:13 UTC, jinqiupeter commented
> @jinqiupeter, please also make the `Explore Case Studies` button in the header menu (Solutions section) and `Success stories` button (Learn section) to point to the Case Studies page. Use Link component(src/components/Link) for that

Done

2023-08-24 08:41 UTC, OleksandrDragun commented on src/components/CasesPage/CasesPage.jsx
> +    <React.Fragment>
It is not necessary to write React.Fragment (if you do not need to pass key). You can just leave empty angle brackets <>.

2023-08-24 09:45 UTC, jinqiupeter commented on src/components/CasesPage/CasesPage.jsx
> +    <React.Fragment>
Thanks, fixed

2023-08-25 07:47 UTC, jinqiupeter commented
> Please contact UX team on how to handle such cases in cards.
> 
> ![image](https://user-images.githubusercontent.com/31861805/262633698-f70fb3f7-265c-42c4-9954-fe3f1b54d5fb.png)

@AmsterGet Confirmed with Dmytro that we will limit the length of title on CMS, which I've already configured it on Contentful.

2023-08-25 08:23 UTC, ViktorSoroka07 approved these changes

2023-08-25 08:23 UTC, AmsterGet approved these changes

2023-08-25 08:29 UTC, merged