feat: Add the Latest From Our Blog
reportportal/reportportal-website pull request #389
Opened 2023-09-08 21:06 UTC by leandrocunha

Added the Latest From Our Blog section to the Landing Page

2023-09-09 21:15 UTC, ViktorSoroka07 submitted a review, later dismissed

2023-09-09 21:15 UTC, ViktorSoroka07 commented on src/components/ArticlePreview/ArticlePreview.jsx
> +          return <ArticlePreviewItem key={post.id} post={post} />;
Let's write this way `{posts.map(post => <ArticlePreviewItem key={post.id} post={post} />`

2023-09-11 10:16 UTC, leandrocunha commented on src/components/ArticlePreview/ArticlePreview.jsx
> +          return <ArticlePreviewItem key={post.id} post={post} />;
@ViktorSoroka07 done

2023-09-11 10:21 UTC, AmsterGet requested changes

2023-09-11 10:21 UTC, AmsterGet commented on src/components/ArticlePreviewItem/ArticlePreviewItem.jsx
> +    <li className={getBlocksWith()} key={post.id}>
I guess the `key` is not needed here as it will be provided in the parent component in case of multiple `ArticlePreviewItem`s.

2023-09-11 10:21 UTC, AmsterGet commented on src/components/ArticlePreview/ArticlePreview.jsx
> +import { ArticlePreviewItem } from '../ArticlePreviewItem/ArticlePreviewItem';
Can be shortened to `import { ArticlePreviewItem } from '../ArticlePreviewItem`.

2023-09-11 10:21 UTC, AmsterGet commented on src/hooks/useLatestFromOurBlog.js
> +          date(formatString: "MMMM Do, YYYY")
Please add the `slug` property as well, since the links currently point to `undefined`
![image](https://github.com/reportportal/reportportal.github.io/assets/31861805/20adf631-5fb4-4807-826f-dd7fa4d9f8e0)

2023-09-11 10:23 UTC, AmsterGet commented on src/components/ArticlePreviewItem/ArticlePreviewItem.jsx
> +    <li className={getBlocksWith()} key={post.id}>
Also component can be shortened by removing explicit `return`:
`() => { return ... }` => `() => (...)`

2023-09-11 11:58 UTC, leandrocunha commented on src/components/ArticlePreview/ArticlePreview.jsx
> +import { ArticlePreviewItem } from '../ArticlePreviewItem/ArticlePreviewItem';
@AmsterGet good catch

2023-09-11 11:59 UTC, leandrocunha commented on src/components/ArticlePreviewItem/ArticlePreviewItem.jsx
> +    <li className={getBlocksWith()} key={post.id}>
@AmsterGet totally right, probably forgot after refactor and split it

2023-09-11 12:11 UTC, ViktorSoroka07 approved these changes, later dismissed

2023-09-11 12:14 UTC, ViktorSoroka07 commented on src/components/LandingPage/LatestFromOurBlog/LatestFromOurBlog.scss
> +    &::-webkit-scrollbar {
Threre is `hide_horizontal_scroll` mixin in `src/components/FeaturesPage/FeaturesPage.scss`. Please move it shared place and use it here. Also please use it in `src/components/QualityAssessmentPage/CommonRequests/CommonRequests.scss`

2023-09-11 12:37 UTC, leandrocunha commented on src/components/LandingPage/LatestFromOurBlog/LatestFromOurBlog.scss
> +    &::-webkit-scrollbar {
@ViktorSoroka07 good suggestion, it's done!

2023-09-11 12:41 UTC, AmsterGet approved these changes

2023-09-11 13:09 UTC, merged