EPMRPP-86795 || add sitemap plugin
reportportal/reportportal-website pull request #414
Opened 2023-10-06 06:15 UTC by Vadim73i

2023-10-06 08:55 UTC, ViktorSoroka07 approved these changes, later dismissed

2023-10-06 17:07 UTC, AmsterGet requested changes

2023-10-06 17:07 UTC, AmsterGet commented on gatsby-config.js
> +        },
I suppose if you [rename](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/#how-to-use) the `url` to `siteUrl` this function can be removed.

2023-10-06 17:07 UTC, AmsterGet commented on gatsby-config.js
> +        },
As the plugin supports glob pattern, it can be simplified by using `excludes` option:

```
        excludes: [
          '/contact-us/taas',
          '/contact-us/taaas',
          '/contact-us/qaaas',
          '/contact-us/saas/**',
          '/contact-us/on-premises/**',
          '/contact-us/qasp',
          '/contact-us/d4j',
          '/contact-us/hlm',
          '/contact-us/qasp/**',
          '/contact-us/d4j/**',
          '/contact-us/hlm/**',
        ],
```

2023-10-10 10:55 UTC, AmsterGet approved these changes

2023-10-10 10:55 UTC, merged