[WIP] Ts migration
reportportal/reportportal-website pull request #430
Opened 2023-10-20 10:16 UTC by leandrocunha

### PR Checklist

* [ ] Have you followed the guidelines in our [Dev Guide](../#readme)
* [ ] Have you lint your code locally prior to submission (`npm run lint`)?
* [ ] Have you run prettier (`npm run format`)?
* [ ] Have you checked that app can be built (`npm run build`)?
* [ ] Have you checked that the build output looks according to design (screen, mobile, desktop) in Figma (`npm run serve`)?

## Visuals

2023-10-20 10:55 UTC, ViktorSoroka07 commented on src/components/DashboardHeader/DashboardHeader.tsx
> +import { createBemBlockBuilder } from '../../utils';
We need to keep this config '@utils'

2023-10-20 10:56 UTC, ViktorSoroka07 commented on src/components/Layout/Navigation/NavMenu/CommunityMenu/icons/ForkIcon.tsx
> +export const ForkIcon: React.FC = () => {
Let's destructure `FC` from react import

import React, { FC } from 'react';

2023-11-02 19:26 UTC, evsbvac commented on src/components/ArrowLink/ArrowLink.tsx
> +export const ArrowLink: React.FC<Props> = ({ text, mode, ...rest }) => (
I think we can import it as { FC } from 'react'

2023-11-02 19:28 UTC, OleksandrDragun commented on src/components/AnimatedList/AnimatedList.tsx
> +export const AnimatedList: React.FC<Props> = ({
I think we can import { FC } from 'react'

2023-11-02 19:33 UTC, OleksandrDragun commented on src/components/Banner/Banner.tsx
> +  children?: React.JSX.Element;
What type is correct? above:
children: React.ReactNode;

2023-11-02 19:40 UTC, OleksandrDragun commented on src/components/ComparePlans/RowSection/FooterColums/FooterColums.tsx
> +import LinkArrow from '../../../../svg/externalLinkArrow.inline.svg';
Why not 
import LinkArrow from '@app/svg/externalLinkArrow.inline.svg';

2023-11-02 19:44 UTC, OleksandrDragun commented on src/components/Layout/Footer/FooterList/FooterList.tsx
> +import { isAbsoluteURL } from '../../../../utils';
from '@app/'

2023-11-02 19:45 UTC, OleksandrDragun commented on src/components/Layout/Layout.tsx
> +  children: JSX.Element;
Third option
![image](https://github.com/reportportal/reportportal.github.io/assets/42969419/038b83b0-410a-4ce3-9980-81446ebd26b3)

2023-11-02 19:48 UTC, OleksandrDragun commented on src/components/OfferPageWrapper/PentagonCard/PentagonCard.tsx
> +import { createBemBlockBuilder, formatNumberWithCommas } from '../../../utils';
```suggestion
import { createBemBlockBuilder, formatNumberWithCommas } from '@app/utils';
```

2023-11-02 19:50 UTC, OleksandrDragun commented on src/components/PricingHero/PricingHero.tsx
> +import { Button, ButtonSwitcher } from '../ButtonSwitcher';
It looks like we have two components inside ../ButtonSwitcher. Is there some another way in TS to import interface and component from one file?

2023-11-02 19:51 UTC, OleksandrDragun commented on src/components/SupportedFrameworks/constants.ts
> +import { iconsFrameworks } from '../../utils/imageSource';
```suggestion
import { iconsFrameworks } from '@app/utils/imageSource';
```

2023-11-02 19:52 UTC, OleksandrDragun commented on src/containers/AcceleratorsPage/D4jPage/D4jPage.tsx
> +import { OfferPageWrapper } from '../../../components/OfferPageWrapper';
```suggestion
import { OfferPageWrapper } from '@app/components/OfferPageWrapper';
```

2023-11-02 19:52 UTC, OleksandrDragun commented on src/containers/AcceleratorsPage/HealeniumPage/HealeniumPage.tsx
> +import { OfferPageWrapper } from '../../../components/OfferPageWrapper';
```suggestion
import { OfferPageWrapper } from '@app/components/OfferPageWrapper';
```

2023-11-02 19:52 UTC, OleksandrDragun commented on src/containers/AcceleratorsPage/QaspPage/QaspPage.tsx
> +import { OfferPageWrapper } from '../../../components/OfferPageWrapper';
```suggestion
import { OfferPageWrapper } from '@app/components/OfferPageWrapper';
```

2023-11-02 19:53 UTC, OleksandrDragun commented on src/containers/BlogPostPage/BlogPostPage.tsx
> +import { SubscriptionBanner } from '../../components/SubscriptionBanner';
```suggestion
import { SubscriptionBanner } from '@app/components/SubscriptionBanner';
```

2023-11-02 19:59 UTC, OleksandrDragun commented on src/components/Layout/Layout.tsx
> +export const Layout = ({ children, className }: Props) => {
Let's use FC<Props>

2023-11-02 20:12 UTC, OleksandrDragun commented on src/containers/CasesPage/CasesPage.tsx
> +interface Case {
Why is interface used here instead of type?

2023-11-02 20:14 UTC, OleksandrDragun commented on src/containers/InstallationPage/InstallationPage.tsx
> +import { Banner } from '../../components/Banner';
```suggestion
import { createBemBlockBuilder, mediaDesktopSm } from '@app/utils';
import { ButtonSwitcher } from '@app/components/ButtonSwitcher';
import { Banner } from '@app/components/Banner';
```

2023-11-02 20:20 UTC, OleksandrDragun commented on src/containers/InstallationPage/IntegrationContent/IntegrationScheme/IntegrationScheme.tsx
> +import { createBemBlockBuilder, mediaTabletSm } from '../../../../utils';
```suggestion
import { createBemBlockBuilder, mediaTabletSm } from '@app/utils';
```

2023-11-02 20:22 UTC, OleksandrDragun commented on src/containers/InstallationPage/Notice/Notice.tsx
> +  children?: ReactNode;
Why is children optional?

2023-11-02 20:22 UTC, OleksandrDragun commented on src/containers/LandingPage/BenefitsForBusiness/BenefitsForBusiness.tsx
> +import { Link } from '../../../components/Link';
```suggestion
import { AnimatedList } from '@app/components/AnimatedList';
import { Link } from '@app/components/Link';
```

2023-11-02 20:23 UTC, OleksandrDragun commented on src/containers/LandingPage/BenefitsForBusiness/constants.ts
> +import { features } from '../../../utils/imageSource';
```suggestion
import { features } from '@app/utils/imageSource';
```

2023-11-02 20:23 UTC, OleksandrDragun commented on src/containers/LandingPage/FeaturesForEngineers/FeaturesForEngineers.tsx
> +import { Link } from '../../../components/Link';
```suggestion
import { AnimatedList } from '@app/components/AnimatedList';
import { Link } from '@app/components/Link';
```

2023-11-02 20:24 UTC, OleksandrDragun commented on src/containers/LandingPage/FeaturesForEngineers/constants.ts
> +import { features } from '../../../utils/imageSource';
```suggestion
import { features } from '@app/utils/imageSource';
```

2023-11-02 20:25 UTC, OleksandrDragun commented on src/containers/LandingPage/LandingPage.tsx
> +import { SubscriptionBanner } from '../../components/SubscriptionBanner';
```suggestion
import { StartTestingWithReportPortal } from '@app/components/StartTestingWithReportPortal';
import { ProcessIntegration } from '@app/components/ProcessIntegration';
import { SubscriptionBanner } from '@app/components/SubscriptionBanner';
```

2023-11-02 20:26 UTC, OleksandrDragun commented on src/containers/OnPremisesPage/OnPremisesPage.tsx
> +import { OfferPageWrapper } from '../../components/OfferPageWrapper';
```suggestion
import { OfferPageWrapper } from '@app/components/OfferPageWrapper';
```

2023-11-02 20:27 UTC, OleksandrDragun commented on src/containers/QualityAssessmentPage/CommonRequests/CommonRequests.tsx
> +import { Heading } from '../../../components/Heading';
```suggestion
import { Heading } from '@app/components/Heading';
```

2023-11-02 20:27 UTC, OleksandrDragun commented on src/containers/QualityAssessmentPage/OurSolution/OurSolution.tsx
> +import { Heading } from '../../../components/Heading';
```suggestion
import { Heading } from '@app/components/Heading';
```

2023-11-02 20:28 UTC, OleksandrDragun commented on src/containers/QualityAssessmentPage/QualityApproach/QualityApproach.tsx
> +import RepeatSvg from '../../../svg/testing/Repeat.svg';
```suggestion
import { UnorderedList } from '@app/components/UnorderedList';
import { Heading } from '@app/components/Heading';
import RepeatSvg from '@app/svg/testing/Repeat.svg';
```

2023-11-02 20:29 UTC, OleksandrDragun commented on src/containers/SassPage/PricingCards/PricingCard/PricingCard.tsx
> +import { Link } from '../../../../components/Link';
```suggestion
import { createBemBlockBuilder, formatNumberWithCommas } from '@app/utils';
import { Link } from '@app/components/Link';
```

2023-11-02 20:30 UTC, OleksandrDragun commented on src/containers/SassPage/SaasPage.tsx
> +import '../../components/OfferPageWrapper/OfferPageWrapper.scss';
```suggestion
import '@app/components/OfferPageWrapper/OfferPageWrapper.scss';
```

2023-11-02 20:31 UTC, OleksandrDragun commented on src/containers/TestAutomationAsServicePage/Benefits/Benefits.tsx
> +import { UnorderedList } from '../../../components/UnorderedList';
```suggestion
import { UnorderedList } from '@app/components/UnorderedList';
```

2023-11-02 20:32 UTC, OleksandrDragun commented on src/containers/TestAutomationAsServicePage/ServiceAria/ServiceAria.tsx
> +import { Heading } from '../../../components/Heading';
```suggestion
import { Heading } from '@app/components/Heading';
```

2023-11-02 20:32 UTC, OleksandrDragun commented on src/containers/TestAutomationAsServicePage/TestAutomationAsServicePage.tsx
> +import { TestingBottomBlock } from '../../components/TestingBottomBlock';
```suggestion
import { DashboardHeader } from '@app/components/DashboardHeader';
import { SpiderBlock } from '@app/components/SpiderBlock';
import { TestingBottomBlock } from '@app/components/TestingBottomBlock';
```

2023-11-02 20:39 UTC, OleksandrDragun commented on src/hooks/useScrollDirection.tsx
> +interface Props {
I would not call it Props because useScrollDirection is not react component.

2023-11-02 20:42 UTC, OleksandrDragun commented on src/templates/BlogPost/blog-post.tsx
> +const BlogPostTemplate = ({ data }: PageProps<DataProps>) => {
`FC<PageProps<DataProps>>`

2023-11-02 20:43 UTC, OleksandrDragun commented on src/templates/case-study/case-study.tsx
> +const CaseStudyTemplate = ({ data }: PageProps<CaseStudyProps>) => {
`FC<PageProps<DataProps>>`

2023-11-02 20:44 UTC, OleksandrDragun commented on src/templates/contact-us/contact-us.tsx
> +const ContactUs = ({ pageContext: { config } }: DataProps) => (
`FC<PageProps<DataProps>>`

2023-11-03 09:46 UTC, ViktorSoroka07 commented on src/components/OfferPageWrapper/PentagonCard/PentagonCard.tsx
> +import { createBemBlockBuilder, formatNumberWithCommas } from '../../../utils';
fixed in #434

2023-11-03 10:26 UTC, ViktorSoroka07 commented on src/components/PricingHero/PricingHero.tsx
> +import { Button, ButtonSwitcher } from '../ButtonSwitcher';
There is an approach to use `import type` notation, but I am opposed to this one as IDE auto import will not use and then you have to manually check this stuff. We can lint though, but it does not bring much value IMO

2023-11-03 10:40 UTC, ViktorSoroka07 commented on src/containers/CasesPage/CasesPage.tsx
> +interface Case {
Just a preference I think. Interfaces are usually used for objects. But there a bunch of articles saying that `type` is far more better

2023-11-05 11:50 UTC, ViktorSoroka07 commented
All unanswered comments are fixed in #435

2023-11-06 14:56 UTC, leandrocunha commented on src/templates/contact-us/contact-us.tsx
> +const ContactUs = ({ pageContext: { config } }: DataProps) => (
@OleksandrDragun fixed

2023-11-06 14:57 UTC, leandrocunha commented on src/templates/case-study/case-study.tsx
> +const CaseStudyTemplate = ({ data }: PageProps<CaseStudyProps>) => {
@OleksandrDragun fixed

2023-11-06 14:57 UTC, leandrocunha commented on src/templates/BlogPost/blog-post.tsx
> +const BlogPostTemplate = ({ data }: PageProps<DataProps>) => {
@OleksandrDragun fixed

2023-11-08 13:45 UTC, AmsterGet requested changes

2023-11-08 13:45 UTC, AmsterGet commented on src/components/ArrowLink/ArrowLink.tsx
> +interface Props {
Can we extend it with `Link` component props to have TS suggestions for the `rest` props?

2023-11-08 13:45 UTC, AmsterGet commented on src/components/Layout/Navigation/NavMenu/LearnMenu/LearnMenu.tsx
> +  isDesktop: boolean;
Should be optional
```suggestion
  isDesktop?: boolean;
```

2023-11-08 13:45 UTC, AmsterGet commented on src/components/Layout/Navigation/NavMenu/CommunityMenu/CommunityMenu.tsx
> +  isDesktop: boolean;
Should be optional as it has a default value.
```suggestion
  isDesktop?: boolean;
```

2023-11-08 13:45 UTC, AmsterGet commented on src/components/Faq/Faq.tsx
> +  showMoreInfoLink: boolean;
Looks like this prop is also optional.
```suggestion
  showMoreInfoLink?: boolean;
```

2023-11-08 13:45 UTC, AmsterGet commented on src/components/Layout/Navigation/NavMenu/OfferingsMenu/OfferingsMenu.tsx
> +  isDesktop: boolean;
```suggestion
  isDesktop?: boolean;
```

2023-11-08 13:45 UTC, AmsterGet commented on src/components/Layout/Navigation/NavMenu/ProductMenu/ProductMenu.tsx
> +  isDesktop: boolean;
```suggestion
  isDesktop?: boolean;
```

2023-11-08 13:45 UTC, AmsterGet commented on src/components/Layout/Navigation/NavMenu/SectionList/SectionItem/SectionItem.tsx
> +  link: string;
```suggestion
  link?: string;
```

2023-11-08 13:45 UTC, AmsterGet commented on src/components/Layout/Navigation/NavMenu/SectionList/SectionItem/SectionItem.tsx
> +  className: string;
```suggestion
  className?: string;
```

2023-11-08 13:45 UTC, AmsterGet commented on src/components/Layout/Navigation/NavMenu/SectionList/SectionList.tsx
> +  showTitle: boolean;
```suggestion
  showTitle?: boolean;
```

2023-11-08 13:45 UTC, AmsterGet commented on src/components/Layout/Navigation/NavMenu/SectionList/SectionList.tsx
> +  className: string;
```suggestion
  className?: string;
```

2023-11-08 13:45 UTC, AmsterGet commented on src/components/Layout/Navigation/NavMenu/SolutionsMenu/SolutionsMenu.tsx
> +  isDesktop: boolean;
```suggestion
  isDesktop?: boolean;
```

2023-11-08 13:45 UTC, AmsterGet commented on src/components/Layout/Navigation/icons/StarIcon.tsx
> +  className: string;
Looks like we can make this prop optional with setting default value ('') for it.

2023-11-08 13:45 UTC, AmsterGet commented on src/components/Layout/Seo/Seo.tsx
> +  }>;
```suggestion
  description?: string;
  lang?: string;
  meta?: ConcatArray<{
    name: string;
    content: string;
    property?: undefined;
  }>;
```

2023-11-08 13:45 UTC, AmsterGet commented on src/components/OfferPageWrapper/TimeScale/TimeScale.tsx
> +  isShifted: boolean;
```suggestion
  isShifted?: boolean;
```

2023-11-08 13:45 UTC, AmsterGet commented on src/components/PricingHero/PricingHero.tsx
> +import { Button, ButtonSwitcher } from '../ButtonSwitcher';
I suppose that easiest solution will be to rename `Button` to smth like `ButtonProps` or even better `ButtonSwitcherProps` to avoid confusing in this case.

2023-11-08 13:45 UTC, AmsterGet commented on src/hooks/useAnimationInterval.tsx
> +  interval: number;
```suggestion
  interval?: number;
```

2023-11-08 16:29 UTC, merged

2023-11-08 18:14 UTC, ViktorSoroka07 commented
@AmsterGet, all comments are fixed in #434