EPMRPP-87634 || Add <meta> tag with value "noindex" to "Contact us" pages
reportportal/reportportal-website pull request #470
Opened 2024-02-16 09:27 UTC by Vadim73i

### PR Checklist

* [ ] Have you followed the guidelines in our [Dev Guide](../#readme)
* [ ] Have you lint your code locally prior to submission (`npm run lint`)?
* [ ] Have you run prettier (`npm run format`)?
* [ ] Have you checked that app can be built (`npm run build`)?
* [ ] Have you checked that the build output looks according to design (screen, mobile, desktop) in Figma (`npm run serve`)?

## Visuals

2024-02-16 18:52 UTC, AmsterGet requested changes

2024-02-16 18:52 UTC, AmsterGet commented on src/components/Layout/Seo/Seo.tsx
> +  noindex?: boolean;
Let's keep using camelCase for props and variables.

2024-02-16 18:52 UTC, AmsterGet commented on src/templates/contact-us/contact-us.tsx
> +  const location = useLocation();
You can use property `url` from the `config` and remove this hook usage.
I see that for some reason this property doesn't mentioned in the props, so please add it to the interface.
It is propagated via `createContactUsConfig` from `src/utils/contactUsConfig.ts`.

2024-02-19 09:34 UTC, ViktorSoroka07 commented
Run prettier command for `npm run format:prettier`. Set it up for your editor

2024-02-19 09:58 UTC, AmsterGet commented on src/templates/contact-us/contact-us.tsx
> +      seoData={{ noIndex: noIndex, ...SEO_DATA.contactUsGeneral }}
```suggestion
      seoData={{ noIndex, ...SEO_DATA.contactUsGeneral }}
```

2024-02-19 11:34 UTC, AmsterGet approved these changes

2024-02-19 11:34 UTC, merged