EPMRPP-89379 || Adjust Installation Page (Google Cloud Marketplace)
reportportal/reportportal-website pull request #476
Opened 2024-02-26 19:43 UTC by Vadim73i

### PR Checklist

* [ ] Have you followed the guidelines in our [Dev Guide](../#readme)
* [ ] Have you lint your code locally prior to submission (`npm run lint`)?
* [ ] Have you run prettier (`npm run format`)?
* [ ] Have you checked that app can be built (`npm run build`)?
* [ ] Have you checked that the build output looks according to design (screen, mobile, desktop) in Figma (`npm run serve`)?

## Visuals

2024-02-27 12:18 UTC, AmsterGet requested changes

2024-02-27 12:18 UTC, AmsterGet commented on src/containers/InstallationPage/InstallationPage.tsx
> +  );
I suppose it would be easier to understand and maintain the sections if they will be grouped by type in a single place.
In this case the properly selection may be done in a single action that's also improve readability.
F.e.

```javascript
const sectionsContent = {
  [DOCKER]: [DockerInstall, DockerDeployingStep, LaunchPortal, IntegrationContent],
  [KUBERNETES]: [KubernetesContent, LaunchPortal, IntegrationContent],
  [GOOGLE_CLOUD]: [GoogleCloudContent, GoogleCloudLaunchPortal, IntegrationContent],
};
// ...
// rendering
{sectionsContent[activeButton].map((section: SectionComponent, index) => (
   <div name={`section-${index}`}>
      <SectionComponent />
   </div>
))};
```

Also in this case you can use values starting from `0` for all sections to define the section ids in the `src/containers/InstallationPage/constants.ts`.

2024-02-28 09:27 UTC, AmsterGet requested changes

2024-02-28 09:27 UTC, AmsterGet commented on src/containers/InstallationPage/InstallationPage.tsx
> +    [GOOGLE_CLOUD]: [GoogleCloudContent, GoogleCloudLaunchPortal, IntegrationContent],
Please move it outside the component.
There is no need to create it during render.

2024-02-28 10:29 UTC, AmsterGet approved these changes

2024-02-28 10:29 UTC, merged

2024-02-28 23:23 UTC, ViktorSoroka07 commented on src/containers/InstallationPage/icons/GoogleCloudIcon.tsx
For future, let's store icons as svg with '.inline.svg` ending and then reference as it is component. It should work just fine

2024-02-29 09:52 UTC, AmsterGet commented on src/containers/InstallationPage/icons/GoogleCloudIcon.tsx
+1, thank you @ViktorSoroka07 !
Looks like @Vadim73i did it to be consistent with other installation page blocks.
I suppose it would be great to add our approach for SVGs inline to the readme. What do you think?

2024-02-29 10:43 UTC, ViktorSoroka07 commented on src/containers/InstallationPage/icons/GoogleCloudIcon.tsx
Agree. Installation page were developed prior to the time when we established the new approach. At least we can add it for new code. Occasionally, I update some of the existing icons to the new approach.

2024-02-29 13:50 UTC, AmsterGet commented on src/containers/InstallationPage/icons/GoogleCloudIcon.tsx
@Vadim73i Please update the readme to mention the above approach if you don't mind.