Youtube carousel
reportportal/reportportal-website pull request #486
Opened 2024-03-12 14:49 UTC by OleksandrDragun

### PR Checklist

* [ ] Have you verified that the PR is pointing to the correct target branch? (`develop` for features/bugfixes, `master` for release/hotfix)?
* [ ] Have you followed the guidelines in our [Dev Guide](../#readme)
* [ ] Have you lint your code locally prior to submission (`npm run lint`)?
* [ ] Have you run prettier (`npm run format`)?
* [ ] Have you checked that app can be built (`npm run build`)?
* [ ] Have you checked that the build output looks according to design (screen, mobile, desktop) in Figma (`npm run serve`)?

## Visuals

2024-03-12 14:57 UTC, ViktorSoroka07 commented on src/containers/CommunityPage/YouTube/utils.ts
> +    const hours = parseInt(match[1] || 0, 10);
Let's create function for this

2024-03-12 14:58 UTC, ViktorSoroka07 commented on src/containers/CommunityPage/YouTube/utils.ts
> +    const minutesStr = minutes.toString().padStart(2, '0');
Let's create function for this

2024-03-14 10:37 UTC, OleksandrDragun commented on src/containers/CommunityPage/YouTube/utils.ts
> +    const hours = parseInt(match[1] || 0, 10);
Done.

2024-03-14 10:37 UTC, OleksandrDragun commented on src/containers/CommunityPage/YouTube/utils.ts
> +    const minutesStr = minutes.toString().padStart(2, '0');
Done.

2024-03-14 10:58 UTC, ViktorSoroka07 commented on src/containers/CommunityPage/YouTube/YouTube.tsx
> +  const isDesktop = useMediaQuery({ query: '(min-width: 1124px)' });
Let's add variable to src/utils/breakpoint.ts and use here

2024-03-14 10:59 UTC, ViktorSoroka07 commented on src/containers/CommunityPage/YouTube/YouTube.tsx
> +  const [isVideoModalOpen, setIsVideoModalOpen] = useState<boolean>(false);
```suggestion
  const [isVideoModalOpen, setIsVideoModalOpen] = useStatefalse);
```

2024-03-14 11:21 UTC, OleksandrDragun commented on src/containers/CommunityPage/YouTube/YouTube.tsx
> +  const isDesktop = useMediaQuery({ query: '(min-width: 1124px)' });
Done.

2024-03-14 11:22 UTC, OleksandrDragun commented on src/containers/CommunityPage/YouTube/YouTube.tsx
> +  const [isVideoModalOpen, setIsVideoModalOpen] = useState<boolean>(false);
Done.

2024-03-14 14:53 UTC, ViktorSoroka07 approved these changes, later dismissed

2024-03-17 10:56 UTC, AmsterGet requested changes

2024-03-17 10:56 UTC, AmsterGet commented on src/containers/LandingPage/Showcase/Carousel/Carousel.tsx
> +export const Carousel: FC<CarouselProps> = memo(({ slides, logoKey }) => (
I suggest to rename it to be more specific, f.e. to `ShowcaseCarousel` or `OrganizationsCarousel`.

2024-03-17 10:56 UTC, AmsterGet commented on gatsby-node.ts
> +    });
In this case appearing new video at YouTube channel will require to rebuild and redeploy the site.
Let's load videos from YouTube at runtime as discussed.

2024-03-17 20:00 UTC, OleksandrDragun commented on src/containers/LandingPage/Showcase/Carousel/Carousel.tsx
> +export const Carousel: FC<CarouselProps> = memo(({ slides, logoKey }) => (
I think if it's placed inside Showcase there is no reason to add such prefix before Carousel. 
I'll change it into the second option, thanks.

2024-03-17 20:06 UTC, OleksandrDragun commented on gatsby-node.ts
> +    });
I did it at first but after some discussion with @ViktorSoroka07 it was reimplemented this way.
Let's discuss it again because I'm in two minds about this )

2024-03-18 07:42 UTC, ViktorSoroka07 commented on gatsby-node.ts
> +    });
On the meeting about requirements for iteration we discussed that it is okay to only load videos at build time

2024-03-18 16:32 UTC, ViktorSoroka07 commented on gatsby-node.ts
> +    });
Same as https://github.com/reportportal/reportportal.github.io/pull/479#discussion_r1528885178

2024-03-18 18:10 UTC, AmsterGet commented on gatsby-node.ts
> +    });
Finally agreed to do it at build time.

2024-03-19 13:31 UTC, AmsterGet submitted a review, later dismissed

2024-03-20 17:37 UTC, AmsterGet approved these changes

2024-03-20 18:42 UTC, merged