EPMRPP-89818 || Use Gatsby Head instead of React Helmet
reportportal/reportportal-website pull request #525
Opened 2024-07-03 08:32 UTC by Vadim73i

Removed icon optimizations.
Reason: no way found to add to Head API yet.

https://status.reportportal.io/youtube?count=10
Changed to 10 because {"error":"provided count exceed max allower value (10)"}

### PR Checklist

* [ ] Have you verified that the PR is pointing to the correct target branch? (`develop` for features/bugfixes, `master` for release/hotfix)?
* [ ] Have you followed the guidelines in our [Dev Guide](../#readme)
* [ ] Have you run prettier (`npm run format`)?
* [ ] Have you checked that the build output looks according to design (screen, mobile, desktop) in Figma (`npm run serve`)?

## Visuals

2024-07-03 08:57 UTC, viktor-soroka-epam commented
Really nice to see that

2024-07-03 09:11 UTC, vsoroka07 commented on src/components/Layout/Navigation/NavMenu/SectionList/SectionItem/SectionItem.tsx
> -            </Helmet>
This code is needed? Do you have an approach to implement it without `helmet`?

2024-07-03 09:11 UTC, vsoroka07 commented on src/components/Layout/Footer/Footer.tsx
> -              )}
This code is needed? Do you have an approach to implement it without `helmet`?

2024-07-03 09:11 UTC, vsoroka07 commented on src/components/Layout/Footer/Footer.tsx
> -                    )}
This code is needed? Do you have an approach to implement it without `helmet`?

2024-07-04 07:12 UTC, Vadim73i commented on src/components/Layout/Navigation/NavMenu/SectionList/SectionItem/SectionItem.tsx
> -            </Helmet>
I haven't found a way to add this using the Head API.
Because The Head function is called only from pages, not from any component. And has limited capabilities in obtaining data.
https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/#properties
We need to think about how we can do this. It is possible to use static data for this.

2024-07-08 10:47 UTC, AmsterGet commented on src/components/Layout/Navigation/NavMenu/SectionList/SectionItem/SectionItem.tsx
> -            </Helmet>
@Vadim73i Can we use [React portal](https://react.dev/reference/react-dom/createPortal) to resolve this?
e.g. smth like this
```javascript
<div>
  {hoverIcon && createPortal(
    <link rel="preload" as="image" href={hoverIcon.url} />,
    document.head
  )}
</div>
```

2024-07-08 10:59 UTC, ViktorSoroka07 commented on src/components/Layout/Navigation/NavMenu/SectionList/SectionItem/SectionItem.tsx
> -            </Helmet>
Good idea. We need to double check that it is added only once

2024-07-08 12:33 UTC, AmsterGet requested changes

2024-07-08 12:33 UTC, AmsterGet commented on src/pages/blog.tsx
> +// eslint-disable-next-line react/no-multi-comp
Does it make sense to disable this rule for 'pages' and 'templates' directories?

2024-07-08 12:33 UTC, AmsterGet commented on gatsby-node.ts
> +    .get('https://status.reportportal.io/youtube?count=10')
![image](https://github.com/reportportal/reportportal.github.io/assets/31861805/d0250670-dd42-413d-9cee-2b7b3d220f18)
According to requirements the number of latest videos should be `12`.
I suppose it should be discussed with Reingold first as the Landing Aggregator maintainer.

2024-07-08 13:59 UTC, AmsterGet commented on gatsby-node.ts
> +    .get('https://status.reportportal.io/youtube?count=10')
The issue was in proper ENV variable absence and already fixed by Hleb, so please revert this change.

2024-07-09 11:08 UTC, AmsterGet approved these changes

2024-07-09 11:20 UTC, merged