EPMRPP-35285 reportportal.io Refactiring
reportportal/reportportal-website pull request #87
Opened 2018-07-20 07:10 UTC by yana95

2018-07-26 14:39 UTC, DiscoElevator requested changes

2018-07-26 14:39 UTC, DiscoElevator commented on src/views/pages/download-page/download-page.scss
> +          border-top: 1.5px solid $COLOR-TOPAZ !important;
Is `!important` really needed here?

2018-07-26 14:39 UTC, DiscoElevator commented on src/views/pages/download-page/download-page.scss
> +    &.nutural{
nutural?

2018-07-26 14:39 UTC, DiscoElevator commented on src/views/pages/download-page/download-page_open/download-page_open.scss
> +    .nutural{
nutural?

2018-07-26 14:39 UTC, DiscoElevator commented on src/views/pages/download-page/download-page.scss
> +    &.recomend {
recommend

2018-07-26 14:39 UTC, DiscoElevator commented on src/views/pages/download-page/download-page_integrate/download-page_integrate.jade
>            a.hide(herf='',data-js-new-window) How to make new integration
`href`
Is it ok that there's a link that takes user to a blank page?

2018-07-26 14:39 UTC, DiscoElevator commented on src/views/pages/download-page/download-page_integrate/download-page_integrate.scss
> +            .contributor {
This looks like a class `beta` from above (line 63). The only difference is `background-color`. I think it can be unified. Something like a class `badge` with an additional classes with different colors: `beta`, `contributor` (or something like that)

2018-08-20 08:03 UTC, yana95 commented on src/views/pages/download-page/download-page_integrate/download-page_integrate.jade
>            a.hide(herf='',data-js-new-window) How to make new integration
Yes, but now it should be hide

2018-08-21 09:09 UTC, DiscoElevator approved these changes

2018-08-21 09:09 UTC, merged